<center> <h1> <b> Smartphone dataset Cleaning

1. We scrap the data from the smartprix website -> we are gonna clean that dataset in this lecture.
2. Firstly as the feature column have all the detail in one column, we have to make multiple columns from the single column
3. Then we have to change price dtype and other have to remove N/A values and duplicated 

In [149]:
import numpy as np
import pandas as pd

In [150]:
smartphone = pd.read_csv('smartprix_mobiles.csv')

In [151]:
smartphone.head()

Serial_No              Product_Name      Price  Rating  Spec_Score  \
0          1  Samsung Galaxy S25 Ultra  ₹1,08,460    4.15        93.0   
1          2     Samsung Galaxy S25 FE    ₹59,999    4.70        86.0   
2          3      OnePlus Nord CE 5 5G    ₹24,998    4.10        83.0   
3          4           Realme Narzo 90    ₹16,999    4.40        72.0   
4          5             Vivo T3 Ultra    ₹22,799    4.10        82.0   

                                      Specifications  \
0  Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC ...   
1  Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC ...   
2  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster...   
3  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi | Dimensity...   
4  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi | Dimensity...   

                                        Product_Link  \
0  https://www.smartprix.com/mobiles/samsung-gala...   
1  https://www.smartprix.com/mobiles/samsung-gala...   
2  https://www.smartprix.com/mobiles/oneplus-nord...   
3  https://www.smartprix.com/mobiles/realme-narzo...   
4  https://www.smartprix.com/mobiles/vivo-t3-ultr...   

                                           Image_URL  
0  https://cdn1.smartprix.com/rx-i3jZEfawx-w280-h...  
1  https://cdn1.smartprix.com/rx-igNNWnxPy-w280-h...  
2  https://cdn1.smartprix.com/rx-i3qMJS8fr-w280-h...  
3  https://cdn1.smartprix.com/rx-iuYfvkRUc-w280-h...  
4  https://cdn1.smartprix.com/rx-iKhtBU6Ja-w280-h...

<span style="font-size: 18px; color: orange"> <b>In this dataset: first we asset it and then clean it, again asset it and then clean it. And do this in loops until the things are fixed.

> As we already studied that: When we want to clean the data, firstly we need to understand that data fully i.e. `Data Assessing`

For data Assesing we have 2 steps:
1. Manual Assesment
2. Programmatical Assessment

In [152]:
# Doing the manual assessment and writing down the observation

<center> <span style="font-size: 26px;"> <b> Data Assessing(manual) </b> </center>

<span style="font-size: 24px;"> <b> Quality Issues </b>

1. **model** - some brands name contain - ram and storage if name contain () with ram and gb written inside bracket then remove that.
2. **model** - some brands are written differently like OPPO in model column
3. Missing values in multiple columns: Product_Name, Rating, Spec_Score, and Specifications all have 8 missing values starting from row 1021
4. **price** - has unneccesary '₹'
5. **price** - has ',' between numbers
6. Incorrect datatype for Price

<span style="font-size: 24px;"> <b> Tidiness Issues </b>  

1. **Specifications** - make these new columns has: dual sim, has 3g, has 4g, has 5g, has_NFC, has_IR_Blaster.
2. **Specifications** - make 2 new columns: RAM and ROM
3. **Specifications** - make 3 new columns: processor name, cores and cpu speed.
4. **Specifications** - make 3 new columns: battery capacity and fast_charging_available, fast charging speed.
5. **Specifications** - make 4 new columns for display: size, resolution_width, resolution_height and frequency.
6. **Specifications** - make 2 new columns for camera: front and rear camera.
7. **Specifications** - make 2 new columns for memory card: supported, extended_upto.
8. **Specifications** - make 1 new columns for os.

Now, do the assessment again and cleaning again.

In [153]:
# Doing the programmatic assessment and writing down the observation.

<center> <span style="font-size: 26px;"> <b> Data Assessing(manual + programmatic) </b> </center>

<span style="font-size: 24px;"> <b> Quality Issues </b>

1. **model** - some brands name contain - ram and storage if name contain () with ram and gb written inside bracket then remove that. `consistency`
2. **model** - some brands are written differently like OPPO in model column `consistency`
3. Missing values in multiple columns: Product_Name, Rating, Spec_Score, and Specifications all have 8 missing values starting from row 1021 `completeness`
4. **price** - has unneccesary '₹' `validity`
5. **price** - has ',' between numbers `validity`
6. Incorrect dtype for Price will be int `validity`
7. Incorrect dtype for Spec_Score will be int `validity`

<span style="font-size: 24px;"> <b> Tidiness Issues </b>  

1. **Specifications** - make these new columns has: dual sim, has 3g, has 4g, has 5g, has_NFC, has_IR_Blaster.
2. **Specifications** - make 2 new columns: RAM and ROM
3. **Specifications** - make 3 new columns: processor name, cores and cpu speed.
4. **Specifications** - make 3 new columns: battery capacity and fast_charging_available, fast charging speed.
5. **Specifications** - make 4 new columns for display: size, resolution_width, resolution_height and frequency.
6. **Specifications** - make 2 new columns for camera: front and rear camera.
7. **Specifications** - make 2 new columns for memory card: supported.
8. **Specifications** - make 1 new columns for os.
9. **Specifications** - drop the Serial_No columns

Now, do the assessment again and cleaning again.

In [154]:
smartphone.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028 entries, 0 to 1027
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Serial_No       1028 non-null   int64  
 1   Product_Name    1020 non-null   object 
 2   Price           1028 non-null   object 
 3   Rating          1020 non-null   float64
 4   Spec_Score      1020 non-null   float64
 5   Specifications  1020 non-null   object 
 6   Product_Link    1028 non-null   object 
 7   Image_URL       1028 non-null   object 
dtypes: float64(2), int64(1), object(5)
memory usage: 64.4+ KB


In [155]:
smartphone.describe()

Serial_No       Rating   Spec_Score
count  1028.000000  1020.000000  1020.000000
mean    514.500000     4.378284    75.650980
std     296.902341     0.233885    17.095579
min       1.000000     3.900000     7.000000
25%     257.750000     4.150000    74.000000
50%     514.500000     4.400000    80.000000
75%     771.250000     4.600000    84.000000
max    1028.000000     4.750000    97.000000

In [156]:
smartphone.duplicated().sum()  # no duplicated data

np.int64(0)

In [157]:
smartphone.isna().sum()

Serial_No         0
Product_Name      8
Price             0
Rating            8
Spec_Score        8
Specifications    8
Product_Link      0
Image_URL         0
dtype: int64

In [158]:
smartphone['Price'].value_counts().reset_index()

Price  count
0    ₹12,999     21
1    ₹24,999     19
2    ₹29,999     18
3    ₹17,999     18
4    ₹19,999     17
..       ...    ...
470  ₹95,999      1
471   ₹4,499      1
472     ₹909      1
473  ₹80,690      1
474   ₹1,444      1

[475 rows x 2 columns]

In [159]:
smartphone[['Price']].drop_duplicates()  # checking uniques values

Price
0     ₹1,08,460
1       ₹59,999
2       ₹24,998
3       ₹16,999
4       ₹22,799
...         ...
1011    ₹22,480
1016     ₹8,989
1018     ₹9,850
1019     ₹1,663
1021  ₹1,59,990

[475 rows x 1 columns]

In [160]:
smartphone['Rating'].value_counts().reset_index().sort_values('count')

Rating  count
17    3.90      2
16    3.95      2
15    4.20     53
14    4.45     57
13    4.70     59
12    4.15     60
11    4.25     61
10    4.40     61
9     4.50     62
7     4.30     63
8     4.05     63
5     4.55     65
6     4.00     65
4     4.10     66
3     4.60     68
2     4.75     69
0     4.65     72
1     4.35     72

In [161]:
smartphone[['Rating']].drop_duplicates().sort_values('Rating')

Rating
812     3.90
369     3.95
6       4.00
32      4.05
2       4.10
0       4.15
38      4.20
16      4.25
5       4.30
8       4.35
3       4.40
7       4.45
21      4.50
31      4.55
11      4.60
18      4.65
1       4.70
19      4.75
1020     NaN

In [162]:
smartphone['Spec_Score'].value_counts().reset_index(
).sort_values('count', ascending=False)

Spec_Score  count
0         82.0     75
1         83.0     63
2         80.0     60
3         79.0     60
4         81.0     60
..         ...    ...
69        54.0      1
70        28.0      1
71        47.0      1
72        34.0      1
73        56.0      1

[74 rows x 2 columns]

In [163]:
smartphone[['Spec_Score']].drop_duplicates().sort_values('Spec_Score')

Spec_Score
832          7.0
663          8.0
562          9.0
715         10.0
527         11.0
...          ...
81          94.0
82          95.0
41          96.0
268         97.0
1020         NaN

[75 rows x 1 columns]

In [164]:
smartphone[['Specifications']].drop_duplicates()

Specifications
0     Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC ...
1     Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC ...
2     Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster...
3     Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi | Dimensity...
4     Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi | Dimensity...
...                                                 ...
1016  Dual Sim, 3G, 4G, VoLTE, Wi-Fi | Unisoc T603, ...
1017  Dual Sim, 3G, 4G, VoLTE, Wi-Fi | Unisoc T606, ...
1018  Dual Sim, 3G, 4G, VoLTE, Wi-Fi | Helio G85, Oc...
1019  Dual Sim | 32 MB RAM, 32 MB inbuilt | 1900 mAh...
1020                                                NaN

[979 rows x 1 columns]

## Data Assessing(Nitish Sir)

### Quality Issues

1. **model** - some brands are written diiferently like OPPO in model column `consistency`
2. **price** - has unneccesary '₹' `validity`
3. **price** - has ',' between numbers `validity`
4. **price** - phone Namotel has a price of 99 `accuracy`
5. **ratings** - missing values `completeness`
6. **processor** - has some incorrect values for some samsung phones(row # -642,647,649,659,667,701,750,759,819,859,883,884,919,927,929,932,1002) `validity`
7. There is ipod on row 756 `validity`
8. **memory** - incorrect values in rows (441,485,534,553,584,610,613,642,647,649,659,667,701,750,759,819,859,884,919,927,929,932,990,1002) `validity`
9. **battery** - incorrect values in rows(113,151,309,365,378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,756,759,764,819,855,859,884,915,916,927,929,932,990,1002) `validity`
10. **display** - sometimes frequency is not available `completeness`
11. **display** - incorrect values in rows(378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,759,764,819,859,884,915,916,927,929,932,990,1002) `validity`
12. certain phones are foldable and the info is scattered `validity`
13. **camera** - words like Dual, Triple and Quad are used to represent number of cameras and front and rear cameras are separated by '&'
14. **camera** - problem with rows (100,113,151,157,161,238,273,308,309,323,324,365,367,378,394,441,450,484,506,534,553,571,572,575,584,610,613,615,630,642,647,649,659,667,684,687,705,711,723,728,750,756,759,764,792,819,846,854,855,858,883,884,896,915,916,927,929,932,945,956,990,995,1002,1016
) `validity`
15. **card** - sometimes contains info about os and camera `validity`
16. **os** - sometimes contains info about bluetooth and fm radio `validity`
17. **os** - issue with rows (324,378) `validity`
18. **os** - sometimes contains os version name like lollipop `consistency`
19. missing values in camera, card and os `completeness`
20. datatype  of price and rating is incorrect `validity`



### Tidiness Issues

1. **sim** - can be split into 3 cols has_5g, has_NFC, has_IR_Blaster
2. **ram** - can be split into 2 cols RAM and ROM
3. **processor** - can be split into processor name, cores and cpu speed.
4. **battery** - can be split into battery capacity, fast_charging_available
5. **display** - can be split into size, resolution_width, resolution_height and frequency
6. **camera** - can be split into front and rear camera
7. **card** - can be split into supported, extended_upto

<span style="font-size: 24px;"> <b>We are done with the data assessment part, now we are gonna do data cleaning and then again assets are the data.

Gonna clean issue with this order   
1- Completeness issue     
2- Validity issue  
3- Accuracy issue  
4- Consistency issue  

In [165]:
clean_smartphone = smartphone.copy()

<center> Completeness

In [166]:
clean_smartphone.tail(8)

Serial_No Product_Name      Price  Rating  Spec_Score Specifications  \
1020       1021          NaN    ₹94,800     NaN         NaN            NaN   
1021       1022          NaN  ₹1,59,990     NaN         NaN            NaN   
1022       1023          NaN  ₹1,49,900     NaN         NaN            NaN   
1023       1024          NaN  ₹1,09,999     NaN         NaN            NaN   
1024       1025          NaN    ₹72,999     NaN         NaN            NaN   
1025       1026          NaN    ₹68,690     NaN         NaN            NaN   
1026       1027          NaN  ₹1,09,999     NaN         NaN            NaN   
1027       1028          NaN    ₹75,999     NaN         NaN            NaN   

                                           Product_Link  \
1020  https://www.smartprix.com/mobiles/samsung-gala...   
1021  https://www.smartprix.com/mobiles/samsung-gala...   
1022  https://www.smartprix.com/mobiles/apple-iphone...   
1023  https://www.smartprix.com/mobiles/vivo-x300-pr...   
1024  https://www.smartprix.com/mobiles/oneplus-15-p...   
1025  https://www.smartprix.com/mobiles/samsung-gala...   
1026  https://www.smartprix.com/mobiles/oppo-find-x9...   
1027  https://www.smartprix.com/mobiles/vivo-x300-pp...   

                                              Image_URL  
1020  https://cdn1.smartprix.com/rx-iz5ZKOGY0-w280-h...  
1021  https://cdn1.smartprix.com/rx-irL2QXDwz-w280-h...  
1022  https://cdn1.smartprix.com/rx-ipwKK83hK-w280-h...  
1023  https://cdn1.smartprix.com/rx-iCS5Q1pzT-w280-h...  
1024  https://cdn1.smartprix.com/rx-iAe49sioe-w280-h...  
1025  https://cdn1.smartprix.com/rx-iGH33GWY9-w280-h...  
1026  https://cdn1.smartprix.com/rx-in2v0JdJP-w280-h...  
1027  https://cdn1.smartprix.com/rx-iP8wcGkpt-w280-h...

In [167]:
# Dropping NaN values
clean_smartphone.dropna(inplace=True)

<center> Validity

In [168]:
# Clean price column

clean_smartphone['Price'] = clean_smartphone['Price'].str.replace(
    '₹', '', regex=False).str.replace(',', '', regex=False)

In [169]:
clean_smartphone['Price']

0       108460
1        59999
2        24998
3        16999
4        22799
         ...  
1015     14499
1016      8989
1017      7999
1018      9850
1019      1663
Name: Price, Length: 1020, dtype: object

In [170]:
# Incorrect dtype of price and spec_score

clean_smartphone['Price'] = clean_smartphone['Price'].astype('Int64')
clean_smartphone['Spec_Score'] = clean_smartphone['Spec_Score'].astype('Int64')

<center> Consistency

In [171]:
# Remove RAM/ROM info inside brackets in Product_name columns

clean_smartphone['Product_Name'] = clean_smartphone['Product_Name'].str.replace(
    r'\s*\([^)]*[Gg][Bb][^)]*\)', '', regex=True).str.strip()

In [172]:
# Standardize brand spelling (OPPO, etc.)

clean_smartphone['Product_Name'] = clean_smartphone['Product_Name'].str.replace(
    r'(?i)^oppo', 'OPPO', regex=True)

In [173]:
clean_smartphone.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1020 entries, 0 to 1019
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Serial_No       1020 non-null   int64  
 1   Product_Name    1020 non-null   object 
 2   Price           1020 non-null   Int64  
 3   Rating          1020 non-null   float64
 4   Spec_Score      1020 non-null   Int64  
 5   Specifications  1020 non-null   object 
 6   Product_Link    1020 non-null   object 
 7   Image_URL       1020 non-null   object 
dtypes: Int64(2), float64(1), int64(1), object(4)
memory usage: 73.7+ KB


<center> Tidiness issues

In [174]:
# ============================================================================
# TIDINESS ISSUES - ROBUST FEATURE EXTRACTION FROM SPECIFICATIONS
# ============================================================================

# Create a copy of Specifications for easier access
clean_smartphone['spec_text'] = clean_smartphone['Specifications'].fillna('')

In [175]:
clean_smartphone['spec_text'].str.contains(
    r'Dual\s*Sim', case=False, regex=True).astype(int)

0       1
1       1
2       1
3       1
4       1
       ..
1015    1
1016    1
1017    1
1018    1
1019    1
Name: spec_text, Length: 1020, dtype: int64

In [176]:
# ===== CONNECTIVITY FEATURES =====
clean_smartphone['has_dual_sim'] = clean_smartphone['spec_text'].str.contains(
    r'Dual\s*Sim', case=False, regex=True).astype(int)
clean_smartphone['has_3g'] = clean_smartphone['spec_text'].str.contains(
    r'\b3G\b', case=False, regex=True).astype(int)
clean_smartphone['has_4g'] = clean_smartphone['spec_text'].str.contains(
    r'\b4G\b', case=False, regex=True).astype(int)
clean_smartphone['has_5g'] = clean_smartphone['spec_text'].str.contains(
    r'\b5G\b', case=False, regex=True).astype(int)
clean_smartphone['has_nfc'] = clean_smartphone['spec_text'].str.contains(
    r'\bNFC\b', case=False, regex=True).astype(int)
clean_smartphone['has_ir_blaster'] = clean_smartphone['spec_text'].str.contains(
    r'IR\s*Blaster', case=False, regex=True).astype(int)

In [177]:
clean_smartphone.head(3)

Serial_No              Product_Name   Price  Rating  Spec_Score  \
0          1  Samsung Galaxy S25 Ultra  108460    4.15          93   
1          2     Samsung Galaxy S25 FE   59999    4.70          86   
2          3      OnePlus Nord CE 5 5G   24998    4.10          83   

                                      Specifications  \
0  Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC ...   
1  Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC ...   
2  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster...   

                                        Product_Link  \
0  https://www.smartprix.com/mobiles/samsung-gala...   
1  https://www.smartprix.com/mobiles/samsung-gala...   
2  https://www.smartprix.com/mobiles/oneplus-nord...   

                                           Image_URL  \
0  https://cdn1.smartprix.com/rx-i3jZEfawx-w280-h...   
1  https://cdn1.smartprix.com/rx-igNNWnxPy-w280-h...   
2  https://cdn1.smartprix.com/rx-i3qMJS8fr-w280-h...   

                                           spec_text  has_dual_sim  has_3g  \
0  Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC ...             1       1   
1  Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC ...             1       1   
2  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster...             1       1   

   has_4g  has_5g  has_nfc  has_ir_blaster  
0       1       1        1               0  
1       1       1        1               0  
2       1       1        0               1

In [178]:
# ===== PROCESSOR INFORMATION =====
import re

# Extract processor name - look for pattern before "Processor" keyword or before core info
processor_pattern = r'\|\s*([^|,]+?)(?:,\s*(?:Octa|Quad|Hexa|Deca|Dual|Single|Nine-Cores)\s*Core|\s+Processor)'
proc_match = clean_smartphone['spec_text'].str.extract(
    processor_pattern, flags=re.IGNORECASE)
clean_smartphone['processor_name'] = proc_match[0].str.strip()

# Extract cores
core_pattern = r'(Octa|Quad|Hexa|Deca|Dual|Single)\s*Core'
clean_smartphone['cores'] = clean_smartphone['spec_text'].str.extract(
    core_pattern, flags=re.IGNORECASE)[0]
clean_smartphone['cores'] = clean_smartphone['cores'].str.title() + ' Core'
clean_smartphone.loc[clean_smartphone['cores'] == 'Nan Core', 'cores'] = pd.NA

# Extract CPU speed in GHz
ghz_pattern = r'([0-9.]+)\s*GHz'
clean_smartphone['cpu_speed_ghz'] = clean_smartphone['spec_text'].str.extract(
    ghz_pattern)[0]
clean_smartphone['cpu_speed_ghz'] = pd.to_numeric(
    clean_smartphone['cpu_speed_ghz'], errors='coerce')

In [179]:
# ===== RAM AND ROM =====
print("  - Extracting RAM and ROM...")
ram_pattern = r'(\d+)\s*GB\s*RAM'
clean_smartphone['ram_gb'] = clean_smartphone['spec_text'].str.extract(
    ram_pattern, flags=re.IGNORECASE)[0]
clean_smartphone['ram_gb'] = pd.to_numeric(
    clean_smartphone['ram_gb'], errors='coerce')

rom_pattern = r'(\d+)\s*GB\s*(?:inbuilt|internal|storage)'
clean_smartphone['rom_gb'] = clean_smartphone['spec_text'].str.extract(
    rom_pattern, flags=re.IGNORECASE)[0]
clean_smartphone['rom_gb'] = pd.to_numeric(
    clean_smartphone['rom_gb'], errors='coerce')

  - Extracting RAM and ROM...


In [180]:
# ===== BATTERY =====
print("  - Extracting battery information...")
battery_pattern = r'(\d+)\s*mAh'
clean_smartphone['battery_capacity_mah'] = clean_smartphone['spec_text'].str.extract(
    battery_pattern)[0]
clean_smartphone['battery_capacity_mah'] = pd.to_numeric(
    clean_smartphone['battery_capacity_mah'], errors='coerce')

clean_smartphone['fast_charging_available'] = clean_smartphone['spec_text'].str.contains(
    r'Fast\s*Charging', case=False, regex=True).astype(int)

fast_charge_pattern = r'(\d+)W\s*Fast\s*Charging'
clean_smartphone['fast_charging_speed_w'] = clean_smartphone['spec_text'].str.extract(
    fast_charge_pattern, flags=re.IGNORECASE)[0]
clean_smartphone['fast_charging_speed_w'] = pd.to_numeric(
    clean_smartphone['fast_charging_speed_w'], errors='coerce')

  - Extracting battery information...


In [181]:
# ===== DISPLAY =====
print("  - Extracting display information...")
display_size_pattern = r'([0-9.]+)\s*inches'
clean_smartphone['display_size_inches'] = clean_smartphone['spec_text'].str.extract(
    display_size_pattern)[0]
clean_smartphone['display_size_inches'] = pd.to_numeric(
    clean_smartphone['display_size_inches'], errors='coerce')

resolution_pattern = r'(\d{3,4})\s*x\s*(\d{3,4})\s*px'
resolution = clean_smartphone['spec_text'].str.extract(resolution_pattern)
clean_smartphone['resolution_width'] = pd.to_numeric(
    resolution[0], errors='coerce')
clean_smartphone['resolution_height'] = pd.to_numeric(
    resolution[1], errors='coerce')

freq_pattern = r'(\d{2,3})\s*Hz\s*Display'
clean_smartphone['display_frequency_hz'] = clean_smartphone['spec_text'].str.extract(
    freq_pattern)[0]
clean_smartphone['display_frequency_hz'] = pd.to_numeric(
    clean_smartphone['display_frequency_hz'], errors='coerce')

  - Extracting display information...


In [182]:
# ===== CAMERA =====
print("  - Extracting camera information...")
# Front camera - look for pattern with "Front Camera"
front_pattern = r'(?:&|\|)\s*(\d+)\s*MP\s*Front\s*Camera'
clean_smartphone['front_camera_mp'] = clean_smartphone['spec_text'].str.extract(
    front_pattern, flags=re.IGNORECASE)[0]
clean_smartphone['front_camera_mp'] = pd.to_numeric(
    clean_smartphone['front_camera_mp'], errors='coerce')

# Rear camera - look for first MP value before "&" or "Rear"
rear_pattern = r'(\d+)\s*MP.*?(?:Rear|Camera)'
rear_matches = clean_smartphone['spec_text'].str.extract(
    rear_pattern, flags=re.IGNORECASE)[0]
clean_smartphone['rear_camera_mp'] = pd.to_numeric(
    rear_matches, errors='coerce')

  - Extracting camera information...


In [183]:
# ===== MEMORY CARD =====
print("  - Extracting memory card information...")
# Check if NOT supported
clean_smartphone['card_supported'] = (~clean_smartphone['spec_text'].str.contains(
    'Memory Card Not Supported|Card Not Supported', case=False, regex=True, na=False)).astype(int)
# Set to NA where spec_text is empty
clean_smartphone.loc[clean_smartphone['spec_text']
                     == '', 'card_supported'] = pd.NA

  - Extracting memory card information...


In [184]:
# ===== OPERATING SYSTEM =====
print("  - Extracting operating system...")
# Look for Android, iOS, or other OS
os_pattern = r'(Android|iOS|Windows|HarmonyOS)\s*(?:v)?([0-9.]+)?'
os_match = clean_smartphone['spec_text'].str.extract(
    os_pattern, flags=re.IGNORECASE)
clean_smartphone['operating_system'] = os_match[0] + \
    ' v' + os_match[1].fillna('')
clean_smartphone['operating_system'] = clean_smartphone['operating_system'].str.replace(
    ' v$', '', regex=True)
clean_smartphone.loc[clean_smartphone['operating_system']
                     == '', 'operating_system'] = pd.NA

  - Extracting operating system...


In [185]:
# ============================================================================
# DROP UNNECESSARY COLUMNS
# ============================================================================

print("\n[6/7] Dropping unnecessary columns...")
columns_to_drop = ['Serial_No', 'spec_text']
clean_smartphone = clean_smartphone.drop(
    columns=columns_to_drop, errors='ignore')
print("✓ Unnecessary columns dropped")


[6/7] Dropping unnecessary columns...
✓ Unnecessary columns dropped


In [186]:
clean_smartphone.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1020 entries, 0 to 1019
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Product_Name             1020 non-null   object 
 1   Price                    1020 non-null   Int64  
 2   Rating                   1020 non-null   float64
 3   Spec_Score               1020 non-null   Int64  
 4   Specifications           1020 non-null   object 
 5   Product_Link             1020 non-null   object 
 6   Image_URL                1020 non-null   object 
 7   has_dual_sim             1020 non-null   int64  
 8   has_3g                   1020 non-null   int64  
 9   has_4g                   1020 non-null   int64  
 10  has_5g                   1020 non-null   int64  
 11  has_nfc                  1020 non-null   int64  
 12  has_ir_blaster           1020 non-null   int64  
 13  processor_name           967 non-null    object 
 14  cores                    962 

In [187]:
# ============================================================================
# FINAL ORGANIZATION
# ============================================================================

print("\n[7/7] Final data organization...")
column_order = ['Product_Name', 'Price', 'Rating', 'Spec_Score', 'Specifications',
                'has_dual_sim', 'has_3g', 'has_4g', 'has_5g', 'has_nfc', 'has_ir_blaster',
                'processor_name', 'cores', 'cpu_speed_ghz',
                'ram_gb', 'rom_gb',
                'battery_capacity_mah', 'fast_charging_available', 'fast_charging_speed_w',
                'display_size_inches', 'resolution_width', 'resolution_height', 'display_frequency_hz',
                'front_camera_mp', 'rear_camera_mp',
                'card_supported',
                'operating_system',
                'Product_Link', 'Image_URL']

existing_columns = [
    col for col in column_order if col in clean_smartphone.columns]
clean_smartphone = clean_smartphone[existing_columns]
print("✓ Columns reordered")


[7/7] Final data organization...
✓ Columns reordered


In [188]:
# ============================================================================
# SAVE AND DISPLAY RESULTS
# ============================================================================

print("\n" + "="*80)
print("Cleaning Complete!")
print("="*80)
print(f"\nFinal Dataset Shape: {clean_smartphone.shape}")
print(f"Columns: {len(clean_smartphone.columns)}")

# Calculate extraction success rates
print("\n" + "="*80)
print("EXTRACTION SUCCESS RATES:")
print("="*80)
total_non_null = len(clean_smartphone) - 8  # Excluding the 8 rows with no data

for col in ['ram_gb', 'rom_gb', 'processor_name', 'cores', 'cpu_speed_ghz', 'battery_capacity_mah',
            'display_size_inches', 'front_camera_mp', 'rear_camera_mp', 'operating_system']:
    if col in clean_smartphone.columns:
        non_null = clean_smartphone[col].notna().sum()
        percentage = (non_null / total_non_null) * 100
        print(f"{col:30s}: {non_null:4d}/{total_non_null:4d} ({percentage:5.1f}%)")

# Display missing value summary
print("\n" + "="*80)
print("Missing Values Summary:")
print("="*80)
missing_summary = clean_smartphone.isnull().sum()
missing_summary = missing_summary[missing_summary > 0].sort_values(
    ascending=False)
print(missing_summary)

# Save cleaned dataset
output_filename = 'smartprix_mobiles_cleaned.csv'
clean_smartphone.to_csv(output_filename, index=False)
print(f"\n✓ Cleaned dataset saved as: {output_filename}")

# Display first few rows
print("\n" + "="*80)
print("Preview of Cleaned Data (first 3 rows):")
print("="*80)
print(clean_smartphone.head(3).to_string())


Cleaning Complete!

Final Dataset Shape: (1020, 29)
Columns: 29

EXTRACTION SUCCESS RATES:
ram_gb                        :  961/1012 ( 95.0%)
rom_gb                        :  959/1012 ( 94.8%)
processor_name                :  967/1012 ( 95.6%)
cores                         :  962/1012 ( 95.1%)
cpu_speed_ghz                 :  914/1012 ( 90.3%)
battery_capacity_mah          : 1020/1012 (100.8%)
display_size_inches           : 1020/1012 (100.8%)
front_camera_mp               :  925/1012 ( 91.4%)
rear_camera_mp                :  996/1012 ( 98.4%)
operating_system              :  938/1012 ( 92.7%)

Missing Values Summary:
display_frequency_hz     151
fast_charging_speed_w    132
cpu_speed_ghz            106
front_camera_mp           95
operating_system          82
rom_gb                    61
ram_gb                    59
cores                     58
processor_name            53
rear_camera_mp            24
resolution_height          9
resolution_width           9
dtype: int64

✓ Cleaned d

---  
---
---
<center>  <span style="font-size: 24px;"> <b> First Iteration is completed.  <center> 
Now lets go second assessment and note down the observation.

In [189]:
smartphone_2 = pd.read_csv('smartprix_mobiles_cleaned.csv')

In [190]:
# Doing manual assessment

<center> <span style="font-size: 26px;"> <b> Data Assessing(manual) </b> </center>

<span style="font-size: 24px;"> <b> Quality Issues </b>

1. **processor_name**: Snapdragon 8 Elite for Galaxy name is wrong its only be Snapdragon 8 Elite `consistency`
2. **processor_name** : index # 495 processor name is wrong '1.5 MHz',  664 name is wrong '256 MHz', 677 name is wrong '512 MHz', 769 name is wrong '1 MHz'. `validity`
3. **processor_name** : There are many others errors in the name. `validity`.
4. OS and rear cameers are missing in keypad mobiles
5. Dual front camers phone does not have front camers values filled in # index 57, 106. 
6. index # 156,157 front camers detail is missing, 
7. Front camers detail are given but empty at many places.
8. Apple mobile display rate is missing
9. Apple mobiles do not have fast charning speed value.
10. If mobile do not support fast charning then fill 0 in the fast charning speed value.
11. If rom size is 1Tb then not fill it in the rom size.
12. Many apples phones do not have ram values in them.
13. If ram or rom value are not in GB then values are empty.
14. Apple and Realme phone do not have processer speed menthion in them.
15. Google phones have problem in the process names and its cores.
16. Also processor issue for Unisoc, MTK MT6739 (# 392, 450)

In [191]:
# Doing programmatic assessment

<center> <span style="font-size: 26px;"> <b> Data Assessing (manual + programmatic) </b> </center>

<span style="font-size: 24px;"> <b> Quality Issues </b>

1. **processor_name**: Snapdragon 8 Elite for Galaxy name is wrong its only be Snapdragon 8 Elite `consistency`
2. **processor_name** : index # 495 processor name is wrong '1.5 MHz',  664 name is wrong '256 MHz', 677 name is wrong '512 MHz', 769 name is wrong '1 MHz'. `validity`
3. **processor_name** : There are many others errors in the name. `validity`.
4. OS and rear cameras are missing in keypad mobiles
5. Dual front camera phone does not have front camera values filled in # index 57, 106. 
6. index # 156,157 front camera detail is missing, 
7. Front camera detail are given but empty at many places.
8. Apple mobile display rate is missing
9. Apple mobiles do not have fast charing speed value.
10. If mobile do not support fast charing then fill 0 in the fast charing speed value.
11. If rom size is 1Tb then not fill it in the rom size.
12. Many apples phones do not have ram values in them.
13. If ram or rom value are not in GB then values are empty.
14. Apple and Realme phone do not have processor speed mention in them.
15. Google phones have problem in the process names and its cores.
16. Also processor issue for Unisoc, MTK MT6739 (# 392, 450)
17. Mobiles which are not smart phones have many missing features
18. 1.3 MHz and 1.5 MHz are in the processor in 3 places each, 512Hz in one place, 5Hz in one place, 1.77 MHz in one place, AMD in one place, `Unisoc T127, MTK MT6739,  Unisoc T107, Unisoc, Unisoc 6533G, Helio 6739, Unisoc 6531F,  Unisoc T127 ` is not taken by the processor name regex, .
19. **cores**: Nine-Cores is not recognized by the regex.
20. **cpu_speed_ghz**: 1.3 MHz, 512 MHz, 1.5 MHz, 208 MHz is not recognized by the regex. and Realme, OPPO, Apple and Google phones do not have cpu_speed_ghz in the specifications.
21. **fast_charging_speed_w**: Apple mobiles do not have fast_charging_speed_w in them.
22. **fast_charging_speed_w**: If fast_charging is 0 then fast_charging_speed_w is NAN.
23. **resolution_width** and **resolution_height**: 3 inches Display, 6.56 inches Display, 2 inches Display these types of things are not taken by the regex.
24. **display_frequency_hz**: All the apples phones and there are many phones where display_frequency_hz is not given.
25. **front_camera_mp**: If front camera MP is in decimal then regex not working hence giving empty value.
26. **front_camera_mp** : If front camera have Dual Front camera then also regex giving empty value.
27. **rear_camera_mp**: If in phone specification there is No Rear Camera is written then you should fill 0 in the rear_camera_mp
28. **rear_camera_mp** : If there are multiple camera then you should mention some how.
29. **operating_system** : Normalize OS name as no need for v10.1 (like this name) [basically no need for decimal precession]
30. **operating_system**: There are  Symbian os which are regex cannot catch.
31. **operating_system**: There are many mobile in which OS is not given and i do not know what to do, as this is my first time data cleaning should i leave the columns blank and let the model building team handel them? as my job only is to clean data.

<span style="font-size: 24px;"> <b> Tidiness Issues </b>  

1. **front_camera_mp** : For dual front camera make another column where write second front camera MP, if phone does not have a second front camera then fill 0

In [192]:
smartphone_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Product_Name             1020 non-null   object 
 1   Price                    1020 non-null   int64  
 2   Rating                   1020 non-null   float64
 3   Spec_Score               1020 non-null   int64  
 4   Specifications           1020 non-null   object 
 5   has_dual_sim             1020 non-null   int64  
 6   has_3g                   1020 non-null   int64  
 7   has_4g                   1020 non-null   int64  
 8   has_5g                   1020 non-null   int64  
 9   has_nfc                  1020 non-null   int64  
 10  has_ir_blaster           1020 non-null   int64  
 11  processor_name           967 non-null    object 
 12  cores                    962 non-null    object 
 13  cpu_speed_ghz            914 non-null    float64
 14  ram_gb                  

In [193]:
smartphone_2.describe(include='all').T

count unique  \
Product_Name               1020    661   
Price                    1020.0    NaN   
Rating                   1020.0    NaN   
Spec_Score               1020.0    NaN   
Specifications             1020    978   
has_dual_sim             1020.0    NaN   
has_3g                   1020.0    NaN   
has_4g                   1020.0    NaN   
has_5g                   1020.0    NaN   
has_nfc                  1020.0    NaN   
has_ir_blaster           1020.0    NaN   
processor_name              967    196   
cores                       962      5   
cpu_speed_ghz             914.0    NaN   
ram_gb                    961.0    NaN   
rom_gb                    959.0    NaN   
battery_capacity_mah     1020.0    NaN   
fast_charging_available  1020.0    NaN   
fast_charging_speed_w     888.0    NaN   
display_size_inches      1020.0    NaN   
resolution_width         1011.0    NaN   
resolution_height        1011.0    NaN   
display_frequency_hz      869.0    NaN   
front_camera_mp           925.0    NaN   
rear_camera_mp            996.0    NaN   
card_supported           1020.0    NaN   
operating_system            938     24   
Product_Link               1020   1019   
Image_URL                  1020    909   

                                                                       top  \
Product_Name                                                   Vivo V60 5G   
Price                                                                  NaN   
Rating                                                                 NaN   
Spec_Score                                                             NaN   
Specifications           Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC | Exyn...   
has_dual_sim                                                           NaN   
has_3g                                                                 NaN   
has_4g                                                                 NaN   
has_5g                                                                 NaN   
has_nfc                                                                NaN   
has_ir_blaster                                                         NaN   
processor_name                                              Dimensity 6300   
cores                                                            Octa Core   
cpu_speed_ghz                                                          NaN   
ram_gb                                                                 NaN   
rom_gb                                                                 NaN   
battery_capacity_mah                                                   NaN   
fast_charging_available                                                NaN   
fast_charging_speed_w                                                  NaN   
display_size_inches                                                    NaN   
resolution_width                                                       NaN   
resolution_height                                                      NaN   
display_frequency_hz                                                   NaN   
front_camera_mp                                                        NaN   
rear_camera_mp                                                         NaN   
card_supported                                                         NaN   
operating_system                                               Android v15   
Product_Link             https://www.smartprix.com/mobiles/vivo-t3x-5g-...   
Image_URL                https://cdn1.smartprix.com/rx-i2up0xlk8-w280-h...   

                        freq          mean          std    min      25%  \
Product_Name               4           NaN          NaN    NaN      NaN   
Price                    NaN  29087.034314  30726.75778  499.0  12499.0   
Rating                   NaN      4.378284     0.233885    3.9     4.15   
Spec_Score               NaN      75.65098    17.095579    7.0     74.0   
Specifications             3           NaN       

In [194]:
smartphone_2[smartphone_2.duplicated()]  # dropping duplicate

Product_Name  Price  Rating  Spec_Score  \
700  Vivo T3x 5G  15499     4.2          78   

                                        Specifications  has_dual_sim  has_3g  \
700  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi | Snapdrago...             1       1   

     has_4g  has_5g  has_nfc  ...  display_size_inches resolution_width  \
700       1       1        0  ...                 6.72           1080.0   

    resolution_height  display_frequency_hz  front_camera_mp  rear_camera_mp  \
700            2408.0                 120.0              8.0            50.0   

     card_supported  operating_system  \
700             1.0       Android v14   

                                          Product_Link  \
700  https://www.smartprix.com/mobiles/vivo-t3x-5g-...   

                                             Image_URL  
700  https://cdn1.smartprix.com/rx-ibpdbuWdX-w280-h...  

[1 rows x 29 columns]

In [195]:
smartphone_2 = smartphone_2.drop(700)

In [196]:
smartphone_2.isnull().sum()

Product_Name                 0
Price                        0
Rating                       0
Spec_Score                   0
Specifications               0
has_dual_sim                 0
has_3g                       0
has_4g                       0
has_5g                       0
has_nfc                      0
has_ir_blaster               0
processor_name              53
cores                       58
cpu_speed_ghz              106
ram_gb                      59
rom_gb                      61
battery_capacity_mah         0
fast_charging_available      0
fast_charging_speed_w      132
display_size_inches          0
resolution_width             9
resolution_height            9
display_frequency_hz       151
front_camera_mp             95
rear_camera_mp              24
card_supported               0
operating_system            82
Product_Link                 0
Image_URL                    0
dtype: int64

## <b> Now checking value counts and null values of all the columns

In [197]:
smartphone_2['processor_name'].value_counts()

processor_name
Dimensity 6300           120
Dimensity 7300            28
Snapdragon 4 Gen2         24
Snapdragon 7 Gen3         22
Snapdragon 7s Gen3        18
                        ... 
UNISOC T7100               1
Helio MT6737               1
1.77 MHz                   1
AMD                        1
Snapdragon 6s Gen1 4G      1
Name: count, Length: 196, dtype: int64

In [198]:
smartphone_2[smartphone_2['processor_name'].isnull()]

Product_Name  Price  Rating  Spec_Score  \
209                 Google Pixel 8A  39999    4.65          76   
353               Google Pixel 8 5G  38999    4.50          75   
391                    HMD Touch 4G   3999    4.55          26   
404         Jio JioPhone Prima 2 4G   2799    4.35          24   
437                Jio Bharat J1 4G   1799    4.35          23   
445          itel Super Guru 4G Max   2399    4.10          15   
448                 iKall I1 Pro 4G   2999    4.45          35   
461              Google Pixel 8 Pro  79999    4.70          79   
517               Nokia 235 4G 2024   3749    4.10          20   
527   Samsung Guru Music 2 Dual Sim    777    4.50          11   
540                Jio Bharat V4 4G    789    4.40          22   
558               Samsung Metro 313    982    4.50          14   
562              Motorola Moto A100    930    4.05           9   
609                         HMD 100    899    4.50           9   
637            Nokia 3210 4G (2024)   3999    4.25          20   
664                Peace Nova 11 4G   5899    4.65          42   
665               iKall Z10 4G 2025   6449    4.00          61   
678                  Lava Action 4G   1799    4.45          17   
680            HMD 130 Music (2025)   1899    4.55          15   
684          BlackZone WINX 4G Plus   3299    4.25          42   
686                   Jio Bharat V3    799    4.75          22   
695             Nokia 220 4G (2024)   3249    4.20          19   
711            Nokia 130 Music 2023   1849    4.20          13   
714           Jio Bharat K1 Karbonn    890    4.40          21   
715         Nokia 105 Dual Sim 2023    984    4.75          10   
718                    Nokia 106 4G   2199    4.20          16   
758               HMD 105 4G (2024)   2199    4.60          17   
822                        Gamma W5   1849    4.45          16   
823                         HMD 101    999    4.75          11   
824                     MTR M16 Pro   4600    4.30          29   
828                      HMD 102 4G   1879    4.40          12   
829                      HMD 101 4G   1899    4.75          12   
832                   Philips E2102   1234    4.70           7   
835              Motorola Moto A200   1149    4.05           9   
857               Nokia 6310 (2024)   3499    4.20          16   
876          Nokia 105 Classic 2023   1049    4.20           7   
883                   Jio Bharat V2    990    4.50          22   
886                  Nokia 105 2023   1199    4.70          10   
941                     GFive A51-C    799    4.15          14   
943                         MTR M15   4600    4.10          28   
945                  Philips E2101C   1075    4.40           7   
950                 Snexian Guru 30    899    4.00          15   
952                   Lava A2 Smart   1079    4.15          11   
962            HMD 150 Music (2025)   2399    4.00          16   
966              Lava A7 Torch Plus   1444    4.30          15   
968                      Amaq Q1 4G   2789    4.25          19   
970            iKall K99 Pro Rugged   1349    4.10          15   
974         Micromax X1i Smart Plus    999    4.30          12   
995                         HMD 105    984    4.70          10   
997                         HMD 110   1164    4.60          12   
1001             Motorola Moto A10V    993    4.00          11   
1002             Motorola Moto A50V   1111    4.75          13   
1019                    itel it5330   1663    4.45          14   

                                         Specifications  has_dual_sim  has_3g  \
209   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC | Tens...             1       1   
353   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC | Tens...             1       1   
391   Dual Sim, 3G, 4G, Wi-Fi | Unisoc T127 | 128 MB...             1       1   
404   Single Sim, 4G, VoLTE, Wi-Fi | 512 MB RAM, 4 G...             0       0   
437   Single Sim, 3G, 4G, VoLTE | 512 MB RAM, 4 GB i.

In [199]:
smartphone_2['cores'].value_counts()

cores
Octa Core      898
Hexa Core       37
Single Core     13
Deca Core       11
Quad Core        2
Name: count, dtype: int64

In [200]:
smartphone_2[smartphone_2['cores'].isnull()]

Product_Name  Price  Rating  Spec_Score  \
209           Google Pixel 8A  39999    4.65          76   
353         Google Pixel 8 5G  38999    4.50          75   
391              HMD Touch 4G   3999    4.55          26   
404   Jio JioPhone Prima 2 4G   2799    4.35          24   
437          Jio Bharat J1 4G   1799    4.35          23   
445    itel Super Guru 4G Max   2399    4.10          15   
448           iKall I1 Pro 4G   2999    4.45          35   
461        Google Pixel 8 Pro  79999    4.70          79   
494        Motorola Moto A300   1199    4.05          14   
517         Nokia 235 4G 2024   3749    4.10          20   
540          Jio Bharat V4 4G    789    4.40          22   
562        Motorola Moto A100    930    4.05           9   
609                   HMD 100    899    4.50           9   
637      Nokia 3210 4G (2024)   3999    4.25          20   
663               Foneme Flip   1600    4.20           8   
664          Peace Nova 11 4G   5899    4.65          42   
676               iKall I7 4G   1549    4.35          32   
678            Lava Action 4G   1799    4.45          17   
680      HMD 130 Music (2025)   1899    4.55          15   
686             Jio Bharat V3    799    4.75          22   
695       Nokia 220 4G (2024)   3249    4.20          19   
711      Nokia 130 Music 2023   1849    4.20          13   
714     Jio Bharat K1 Karbonn    890    4.40          21   
715   Nokia 105 Dual Sim 2023    984    4.75          10   
718              Nokia 106 4G   2199    4.20          16   
758         HMD 105 4G (2024)   2199    4.60          17   
768             Jio Bharat B2   1399    4.65          15   
823                   HMD 101    999    4.75          11   
824               MTR M16 Pro   4600    4.30          29   
828                HMD 102 4G   1879    4.40          12   
829                HMD 101 4G   1899    4.75          12   
832             Philips E2102   1234    4.70           7   
835        Motorola Moto A200   1149    4.05           9   
857         Nokia 6310 (2024)   3499    4.20          16   
875        Motorola Moto A10G    993    4.10          13   
876    Nokia 105 Classic 2023   1049    4.20           7   
883             Jio Bharat V2    990    4.50          22   
886            Nokia 105 2023   1199    4.70          10   
942               Mixx M1 312    628    4.30          16   
943                   MTR M15   4600    4.10          28   
944               iKall I4 4G   1599    4.30          16   
945            Philips E2101C   1075    4.40           7   
948          Snexian Bold 40K   1149    4.25          12   
949          Snexian Rock R21    699    4.05          15   
950           Snexian Guru 30    899    4.00          15   
959     Lava Hero Shakti 2025    909    4.50          17   
961          Snexian Bravo 4G   1599    4.00          14   
962      HMD 150 Music (2025)   2399    4.00          16   
966        Lava A7 Torch Plus   1444    4.30          15   
968                Amaq Q1 4G   2789    4.25          19   
970      iKall K99 Pro Rugged   1349    4.10          15   
989      Hotline Classic Zeus    499    4.60           7   
990                GFive A7-C    549    4.75           8   
995                   HMD 105    984    4.70          10   
997                   HMD 110   1164    4.60          12   
1001       Motorola Moto A10V    993    4.00          11   
1002       Motorola Moto A50V   1111    4.75          13   
1019              itel it5330   1663    4.45          14   

                                         Specifications  has_dual_sim  has_3g  \
209   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC | Tens...             1       1   
353   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC | Tens...             1       1   
391   Dual Sim, 3G, 4G, Wi-Fi | Unisoc T127 | 128 MB...             1       1   
404   Single Sim, 4G, VoLTE, Wi-Fi | 512 MB RAM, 4 G...             0       0   
437   Single Sim, 3G, 4G, VoLTE | 512 MB RAM, 4 GB i...             0  

In [201]:
smartphone_2['cpu_speed_ghz'].value_counts()

cpu_speed_ghz
2.40    209
2.50    119
2.20    108
3.20     43
2.60     42
3.00     34
2.00     34
2.80     33
2.30     31
3.35     28
1.80     25
2.63     22
3.25     15
3.30     15
3.10     14
4.47     13
4.32      9
4.04      9
2.85      9
2.70      8
4.60      7
4.21      7
4.05      7
2.84      6
2.05      6
2.90      6
1.60      6
3.63      5
3.36      5
3.78      5
1.00      4
3.40      4
3.22      4
3.46      3
3.39      3
3.84      2
3.11      2
2.10      2
1.40      2
2.96      1
3.05      1
1.70      1
2.65      1
2.73      1
1.82      1
1.25      1
Name: count, dtype: int64

In [202]:
smartphone_2[smartphone_2['cpu_speed_ghz'].isnull()]

Product_Name   Price  Rating  Spec_Score  \
3             Realme Narzo 90   16999    4.40          72   
7               Realme P4x 5G   14942    4.45          67   
14            Apple iPhone 17   82900    4.60          79   
46    Apple iPhone 17 Pro Max  149900    4.25          82   
50           Realme P4 Pro 5G   24699    4.55          73   
...                       ...     ...     ...         ...   
997                   HMD 110    1164    4.60          12   
1001       Motorola Moto A10V     993    4.00          11   
1002       Motorola Moto A50V    1111    4.75          13   
1016              itel A70 4G    8989    4.60          60   
1019              itel it5330    1663    4.45          14   

                                         Specifications  has_dual_sim  has_3g  \
3     Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi | Dimensity...             1       1   
7     Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi | Dimensity...             1       1   
14    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC | Appl...             1       1   
46    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC | Appl...             1       1   
50    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster...             1       1   
...                                                 ...           ...     ...   
997   Dual Sim | No Wifi | 4 MB RAM, 4 MB inbuilt | ...             1       0   
1001  Dual Sim | 4 MB RAM, 4 MB inbuilt | 800 mAh Ba...             1       0   
1002  Dual Sim | 4 MB RAM, 4 MB inbuilt | 1750 mAh B...             1       0   
1016  Dual Sim, 3G, 4G, VoLTE, Wi-Fi | Unisoc T603, ...             1       1   
1019  Dual Sim | 32 MB RAM, 32 MB inbuilt | 1900 mAh...             1       0   

      has_4g  has_5g  has_nfc  ...  display_size_inches resolution_width  \
3          1       1        0  ...                 6.57           1080.0   
7          1       1        0  ...                 6.72           1080.0   
14         1       1        1  ...                 6.30           1206.0   
46         1       1        1  ...                 6.90           1320.0   
50         1       1        0  ...                 6.80           1280.0   
...      ...     ...      ...  ...                  ...              ...   
997        0       0        0  ...                 2.00            120.0   
1001       0       0        0  ...                 1.80            160.0   
1002       0       0        0  ...                 1.80            160.0   
1016       1       0        0  ...                 6.60            720.0   
1019       0       0        0  ...                 2.80            320.0   

     resolution_height  display_frequency_hz  front_camera_mp  rear_camera_mp  \
3               2372.0                 120.0             50.0            50.0   
7               2400.0                 144.0              8.0            50.0   
14              2622.0                 120.0             18.0            48.0   
46              2868.0                 120.0             18.0            48.0   
50              2800.0                 144.0             50.0            50.0   
...                ...                   ...              ...             ...   
997              160.0                   NaN              NaN             NaN   
1001             128.0                   NaN              NaN             NaN   
1002             128.0                   NaN              NaN             3.0   
1016            1612.0                   NaN              8.0            13.0   
1019             240.0                   NaN              NaN             3.0   

      card_supported  operating_system  \
3                1.0       Android v15   
7                1.0       Android v15   
14               0.0           iOS v26   
46               0.0           iOS v26   
50               1.0       Android v15   
...              ...               ...   
997              1.0               NaN   
1001             1.0               NaN   
1002             1.0               NaN   
1016 

In [203]:
smartphone_2['battery_capacity_mah'].value_counts()

battery_capacity_mah
5000    374
6000    113
5500     71
7000     67
6500     29
       ... 
4250      1
1200      1
2575      1
3500      1
1900      1
Name: count, Length: 101, dtype: int64

In [204]:
smartphone_2['fast_charging_available'].value_counts()

fast_charging_available
1    940
0     79
Name: count, dtype: int64

In [205]:
smartphone_2['fast_charging_speed_w'].value_counts()

fast_charging_speed_w
45.0     137
80.0     125
25.0     104
33.0      92
18.0      73
90.0      53
15.0      52
44.0      43
67.0      37
120.0     34
100.0     25
10.0      22
30.0      19
68.0      15
60.0      10
66.0       8
65.0       8
50.0       7
20.0       6
70.0       3
37.0       2
27.0       2
125.0      2
35.0       2
150.0      2
75.0       2
23.0       1
5.0        1
Name: count, dtype: int64

In [206]:
smartphone_2[smartphone_2['fast_charging_speed_w'].isnull()]

Product_Name   Price  Rating  Spec_Score  \
14            Apple iPhone 17   82900    4.60          79   
25            Apple iPhone 16   64590    4.75          85   
46    Apple iPhone 17 Pro Max  149900    4.25          82   
49            Apple iPhone 15   54790    4.65          81   
72        Apple iPhone 16 Pro  103990    4.25          87   
...                       ...     ...     ...         ...   
995                   HMD 105     984    4.70          10   
997                   HMD 110    1164    4.60          12   
1001       Motorola Moto A10V     993    4.00          11   
1002       Motorola Moto A50V    1111    4.75          13   
1019              itel it5330    1663    4.45          14   

                                         Specifications  has_dual_sim  has_3g  \
14    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC | Appl...             1       1   
25    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC | Bion...             1       1   
46    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC | Appl...             1       1   
49    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC | Bion...             1       1   
72    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC | Bion...             1       1   
...                                                 ...           ...     ...   
995   Dual Sim | No Wifi | 4 MB RAM, 4 MB inbuilt | ...             1       0   
997   Dual Sim | No Wifi | 4 MB RAM, 4 MB inbuilt | ...             1       0   
1001  Dual Sim | 4 MB RAM, 4 MB inbuilt | 800 mAh Ba...             1       0   
1002  Dual Sim | 4 MB RAM, 4 MB inbuilt | 1750 mAh B...             1       0   
1019  Dual Sim | 32 MB RAM, 32 MB inbuilt | 1900 mAh...             1       0   

      has_4g  has_5g  has_nfc  ...  display_size_inches resolution_width  \
14         1       1        1  ...                  6.3           1206.0   
25         1       1        1  ...                  6.1           1179.0   
46         1       1        1  ...                  6.9           1320.0   
49         1       1        1  ...                  6.1           1179.0   
72         1       1        1  ...                  6.3           1206.0   
...      ...     ...      ...  ...                  ...              ...   
995        0       0        0  ...                  1.8            120.0   
997        0       0        0  ...                  2.0            120.0   
1001       0       0        0  ...                  1.8            160.0   
1002       0       0        0  ...                  1.8            160.0   
1019       0       0        0  ...                  2.8            320.0   

     resolution_height  display_frequency_hz  front_camera_mp  rear_camera_mp  \
14              2622.0                 120.0             18.0            48.0   
25              2556.0                   NaN             12.0            48.0   
46              2868.0                 120.0             18.0            48.0   
49              2556.0                   NaN             12.0            48.0   
72              2622.0                 120.0             12.0            48.0   
...                ...                   ...              ...             ...   
995              160.0                   NaN              NaN             NaN   
997              160.0                   NaN              NaN             NaN   
1001             128.0                   NaN              NaN             NaN   
1002             128.0                   NaN              NaN             3.0   
1019             240.0                   NaN              NaN             3.0   

      card_supported  operating_system  \
14               0.0           iOS v26   
25               0.0           iOS v18   
46               0.0           iOS v26   
49               0.0           iOS v17   
72               0.0           iOS v18   
...              ...               ...   
995              1.0               NaN   
997              1.0               NaN   
1001             1.0               NaN   
1002 

In [207]:
smartphone_2['display_size_inches'].value_counts()

display_size_inches
6.67    176
6.70    145
6.78     88
6.77     57
6.74     46
       ... 
5.50      1
6.38      1
4.00      1
6.26      1
5.99      1
Name: count, Length: 63, dtype: int64

In [208]:
smartphone_2['resolution_width'].value_counts()

resolution_width
1080.0    454
720.0     202
1220.0     39
1260.0     37
1440.0     34
1280.0     25
240.0      23
1272.0     22
1264.0     19
1256.0     10
1206.0      9
1224.0      9
320.0       8
120.0       8
1240.0      8
1216.0      7
1600.0      7
1320.0      7
1084.0      7
128.0       6
1200.0      6
160.0       6
1170.0      6
1179.0      5
1290.0      5
412.0       5
1344.0      4
480.0       4
1236.0      3
2400.0      3
1968.0      3
1856.0      3
2268.0      2
1640.0      2
1812.0      2
2200.0      2
2000.0      1
1284.0      1
1560.0      1
2076.0      1
828.0       1
2152.0      1
1768.0      1
384.0       1
Name: count, dtype: int64

In [209]:
smartphone_2[smartphone_2['resolution_width'].isnull()]

Product_Name  Price  Rating  Spec_Score  \
445  itel Super Guru 4G Max   2399    4.10          15   
664        Peace Nova 11 4G   5899    4.65          42   
828              HMD 102 4G   1879    4.40          12   
829              HMD 101 4G   1899    4.75          12   
832           Philips E2102   1234    4.70           7   
888       Motorola Moto G14   8990    4.05          67   
942             Mixx M1 312    628    4.30          16   
945          Philips E2101C   1075    4.40           7   
968              Amaq Q1 4G   2789    4.25          19   

                                        Specifications  has_dual_sim  has_3g  \
445  Dual Sim, 3G, 4G, VoLTE | 64 MB RAM | 2000 mAh...             1       1   
664  Dual Sim, 3G, 4G, Wi-Fi | Helio 6739 | 4 GB RA...             1       1   
828  Dual Sim, 4G | Unisoc 8910 FF-S | 24 MB RAM, 1...             1       0   
829  Dual Sim, 4G | Unisoc 8910 FF-S | 1000 mAh Bat...             1       0   
832  Unisoc SC6531E | 4 MB RAM, 4 MB inbuilt | 1000...             0       0   
888  Dual Sim, 3G, 4G, VoLTE, Wi-Fi | Tiger T616, O...             1       1   
942  Dual Sim, 4G | 5 MHz Processor | 32 GB inbuilt...             1       0   
945  32 MB RAM, 32 MB inbuilt | 1000 mAh Battery | ...             0       0   
968  Dual Sim, 3G, 4G | 512 MB RAM | 3500 mAh Batte...             1       1   

     has_4g  has_5g  has_nfc  ...  display_size_inches resolution_width  \
445       1       0        0  ...                 3.00              NaN   
664       1       0        0  ...                 6.56              NaN   
828       1       0        0  ...                 2.00              NaN   
829       1       0        0  ...                 2.00              NaN   
832       0       0        0  ...                 1.77              NaN   
888       1       0        0  ...                 6.50              NaN   
942       1       0        0  ...                 1.80              NaN   
945       0       0        0  ...                 1.77              NaN   
968       1       0        0  ...                 2.80              NaN   

    resolution_height  display_frequency_hz  front_camera_mp  rear_camera_mp  \
445               NaN                   NaN              NaN             3.0   
664               NaN                   NaN              5.0            20.0   
828               NaN                   NaN              NaN             NaN   
829               NaN                   NaN              NaN             NaN   
832               NaN                   NaN              NaN             8.0   
888               NaN                   NaN              8.0            50.0   
942               NaN                   NaN              NaN             2.0   
945               NaN                   NaN              NaN             NaN   
968               NaN                   NaN              NaN             6.0   

     card_supported  operating_system  \
445             1.0               NaN   
664             1.0               NaN   
828             1.0               NaN   
829             1.0               NaN   
832             1.0               NaN   
888             1.0       Android v13   
942             1.0               NaN   
945             1.0               NaN   
968             1.0               NaN   

                                          Product_Link  \
445  https://www.smartprix.com/mobiles/itel-super-g...   
664  https://www.smartprix.com/mobiles/peace-nova-1...   
828  https://www.smartprix.com/mobiles/hmd-102-4g-p...   
829  https://www.smartprix.com/mobiles/hmd-101-4g-p...   
832  https://www.smartprix.com/mobiles/philips-e210...   
888  https://www.smartprix.com/mobiles/motorola-mot...   
942  https://www.smartprix.com/mobiles/mixx-m1-312-...   
945  https://www.smartprix.com/mobiles/philips-e210...   
968  https://www.smartprix.com/mobiles/amaq-q1-4g-p...   

                                             Image_URL  
445  https://cdn1.smartprix.com/

In [210]:
smartphone_2[smartphone_2['resolution_height'].isnull()]

Product_Name  Price  Rating  Spec_Score  \
445  itel Super Guru 4G Max   2399    4.10          15   
664        Peace Nova 11 4G   5899    4.65          42   
828              HMD 102 4G   1879    4.40          12   
829              HMD 101 4G   1899    4.75          12   
832           Philips E2102   1234    4.70           7   
888       Motorola Moto G14   8990    4.05          67   
942             Mixx M1 312    628    4.30          16   
945          Philips E2101C   1075    4.40           7   
968              Amaq Q1 4G   2789    4.25          19   

                                        Specifications  has_dual_sim  has_3g  \
445  Dual Sim, 3G, 4G, VoLTE | 64 MB RAM | 2000 mAh...             1       1   
664  Dual Sim, 3G, 4G, Wi-Fi | Helio 6739 | 4 GB RA...             1       1   
828  Dual Sim, 4G | Unisoc 8910 FF-S | 24 MB RAM, 1...             1       0   
829  Dual Sim, 4G | Unisoc 8910 FF-S | 1000 mAh Bat...             1       0   
832  Unisoc SC6531E | 4 MB RAM, 4 MB inbuilt | 1000...             0       0   
888  Dual Sim, 3G, 4G, VoLTE, Wi-Fi | Tiger T616, O...             1       1   
942  Dual Sim, 4G | 5 MHz Processor | 32 GB inbuilt...             1       0   
945  32 MB RAM, 32 MB inbuilt | 1000 mAh Battery | ...             0       0   
968  Dual Sim, 3G, 4G | 512 MB RAM | 3500 mAh Batte...             1       1   

     has_4g  has_5g  has_nfc  ...  display_size_inches resolution_width  \
445       1       0        0  ...                 3.00              NaN   
664       1       0        0  ...                 6.56              NaN   
828       1       0        0  ...                 2.00              NaN   
829       1       0        0  ...                 2.00              NaN   
832       0       0        0  ...                 1.77              NaN   
888       1       0        0  ...                 6.50              NaN   
942       1       0        0  ...                 1.80              NaN   
945       0       0        0  ...                 1.77              NaN   
968       1       0        0  ...                 2.80              NaN   

    resolution_height  display_frequency_hz  front_camera_mp  rear_camera_mp  \
445               NaN                   NaN              NaN             3.0   
664               NaN                   NaN              5.0            20.0   
828               NaN                   NaN              NaN             NaN   
829               NaN                   NaN              NaN             NaN   
832               NaN                   NaN              NaN             8.0   
888               NaN                   NaN              8.0            50.0   
942               NaN                   NaN              NaN             2.0   
945               NaN                   NaN              NaN             NaN   
968               NaN                   NaN              NaN             6.0   

     card_supported  operating_system  \
445             1.0               NaN   
664             1.0               NaN   
828             1.0               NaN   
829             1.0               NaN   
832             1.0               NaN   
888             1.0       Android v13   
942             1.0               NaN   
945             1.0               NaN   
968             1.0               NaN   

                                          Product_Link  \
445  https://www.smartprix.com/mobiles/itel-super-g...   
664  https://www.smartprix.com/mobiles/peace-nova-1...   
828  https://www.smartprix.com/mobiles/hmd-102-4g-p...   
829  https://www.smartprix.com/mobiles/hmd-101-4g-p...   
832  https://www.smartprix.com/mobiles/philips-e210...   
888  https://www.smartprix.com/mobiles/motorola-mot...   
942  https://www.smartprix.com/mobiles/mixx-m1-312-...   
945  https://www.smartprix.com/mobiles/philips-e210...   
968  https://www.smartprix.com/mobiles/amaq-q1-4g-p...   

                                             Image_URL  
445  https://cdn1.smartprix.com/

In [211]:
smartphone_2['display_frequency_hz'].value_counts()

display_frequency_hz
120.0    654
90.0     131
144.0     77
165.0      6
Name: count, dtype: int64

In [212]:
smartphone_2[smartphone_2['display_frequency_hz'].isnull()]

Product_Name  Price  Rating  Spec_Score  \
25         Apple iPhone 16  64590    4.75          85   
49         Apple iPhone 15  54790    4.65          81   
90    Apple iPhone 15 Plus  59994    4.75          82   
127        Apple iPhone 13  45690    4.35          76   
128   Apple iPhone 16 Plus  71990    4.05          82   
...                    ...    ...     ...         ...   
997                HMD 110   1164    4.60          12   
1001    Motorola Moto A10V    993    4.00          11   
1002    Motorola Moto A50V   1111    4.75          13   
1016           itel A70 4G   8989    4.60          60   
1019           itel it5330   1663    4.45          14   

                                         Specifications  has_dual_sim  has_3g  \
25    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC | Bion...             1       1   
49    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC | Bion...             1       1   
90    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC | Bion...             1       1   
127   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC | Bion...             1       1   
128   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC | Bion...             1       1   
...                                                 ...           ...     ...   
997   Dual Sim | No Wifi | 4 MB RAM, 4 MB inbuilt | ...             1       0   
1001  Dual Sim | 4 MB RAM, 4 MB inbuilt | 800 mAh Ba...             1       0   
1002  Dual Sim | 4 MB RAM, 4 MB inbuilt | 1750 mAh B...             1       0   
1016  Dual Sim, 3G, 4G, VoLTE, Wi-Fi | Unisoc T603, ...             1       1   
1019  Dual Sim | 32 MB RAM, 32 MB inbuilt | 1900 mAh...             1       0   

      has_4g  has_5g  has_nfc  ...  display_size_inches resolution_width  \
25         1       1        1  ...                  6.1           1179.0   
49         1       1        1  ...                  6.1           1179.0   
90         1       1        1  ...                  6.7           1290.0   
127        1       1        1  ...                  6.1           1170.0   
128        1       1        1  ...                  6.7           1290.0   
...      ...     ...      ...  ...                  ...              ...   
997        0       0        0  ...                  2.0            120.0   
1001       0       0        0  ...                  1.8            160.0   
1002       0       0        0  ...                  1.8            160.0   
1016       1       0        0  ...                  6.6            720.0   
1019       0       0        0  ...                  2.8            320.0   

     resolution_height  display_frequency_hz  front_camera_mp  rear_camera_mp  \
25              2556.0                   NaN             12.0            48.0   
49              2556.0                   NaN             12.0            48.0   
90              2796.0                   NaN             12.0            48.0   
127             2532.0                   NaN             12.0            12.0   
128             2796.0                   NaN             12.0            48.0   
...                ...                   ...              ...             ...   
997              160.0                   NaN              NaN             NaN   
1001             128.0                   NaN              NaN             NaN   
1002             128.0                   NaN              NaN             3.0   
1016            1612.0                   NaN              8.0            13.0   
1019             240.0                   NaN              NaN             3.0   

      card_supported  operating_system  \
25               0.0           iOS v18   
49               0.0           iOS v17   
90               0.0           iOS v17   
127              0.0           iOS v15   
128              0.0           iOS v18   
...              ...               ...   
997              1.0               NaN   
1001             1.0               NaN   
1002             1.0               NaN   
1016             1.0       Android v13   
1019    

In [213]:
smartphone_2['front_camera_mp'].value_counts()

front_camera_mp
16.0    190
8.0     176
32.0    158
50.0    109
5.0      87
13.0     80
12.0     60
20.0     29
10.0     15
18.0     12
42.0      5
40.0      2
2.0       1
Name: count, dtype: int64

In [214]:
smartphone_2[smartphone_2['front_camera_mp'].isnull()]

Product_Name   Price  Rating  Spec_Score  \
56             Xiaomi 14 Civi   26999    4.70          87   
105            Xiaomi 14 Civi   36999    4.00          88   
154        Google Pixel 10 5G   70170    4.50          87   
155            Google Pixel 9   61999    4.15          87   
202        Google Pixel 6 Pro   29499    4.75          86   
...                       ...     ...     ...         ...   
996   Samsung Galaxy Z Fold 6  185999    4.25          91   
997                   HMD 110    1164    4.60          12   
1001       Motorola Moto A10V     993    4.00          11   
1002       Motorola Moto A50V    1111    4.75          13   
1019              itel it5330    1663    4.45          14   

                                         Specifications  has_dual_sim  has_3g  \
56    Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC,...             1       1   
105   Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC,...             1       1   
154   Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC ...             1       1   
155   Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC ...             1       1   
202   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC | Tens...             1       1   
...                                                 ...           ...     ...   
996   Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC ...             1       1   
997   Dual Sim | No Wifi | 4 MB RAM, 4 MB inbuilt | ...             1       0   
1001  Dual Sim | 4 MB RAM, 4 MB inbuilt | 800 mAh Ba...             1       0   
1002  Dual Sim | 4 MB RAM, 4 MB inbuilt | 1750 mAh B...             1       0   
1019  Dual Sim | 32 MB RAM, 32 MB inbuilt | 1900 mAh...             1       0   

      has_4g  has_5g  has_nfc  ...  display_size_inches resolution_width  \
56         1       1        1  ...                 6.55           1236.0   
105        1       1        1  ...                 6.55           1236.0   
154        1       1        1  ...                 6.30           1080.0   
155        1       1        1  ...                 6.30           1080.0   
202        1       1        1  ...                 6.71           1440.0   
...      ...     ...      ...  ...                  ...              ...   
996        1       1        1  ...                 7.60           1856.0   
997        0       0        0  ...                 2.00            120.0   
1001       0       0        0  ...                 1.80            160.0   
1002       0       0        0  ...                 1.80            160.0   
1019       0       0        0  ...                 2.80            320.0   

     resolution_height  display_frequency_hz  front_camera_mp  rear_camera_mp  \
56              2750.0                 120.0              NaN            50.0   
105             2750.0                 120.0              NaN            50.0   
154             2424.0                 120.0              NaN            48.0   
155             2424.0                 120.0              NaN            50.0   
202             3120.0                 120.0              NaN            50.0   
...                ...                   ...              ...             ...   
996             2160.0                 120.0              NaN            50.0   
997              160.0                   NaN              NaN             NaN   
1001             128.0                   NaN              NaN             NaN   
1002             128.0                   NaN              NaN             3.0   
1019             240.0                   NaN              NaN             3.0   

      card_supported  operating_system  \
56               1.0       Android v14   
105              1.0       Android v14   
154              1.0       Android v16   
155              1.0       Android v14   
202              1.0       Android v12   
...              ...               ...   
996              0.0               NaN   
997              1.0               NaN   
1001             1.0               NaN   
1002 

In [215]:
smartphone_2['rear_camera_mp'].value_counts()

rear_camera_mp
50.0     633
64.0      78
48.0      62
108.0     47
13.0      39
200.0     31
3.0       26
32.0      25
8.0       20
12.0      15
2.0        6
20.0       4
5.0        4
16.0       2
180.0      1
40.0       1
6.0        1
Name: count, dtype: int64

In [216]:
smartphone_2[smartphone_2['rear_camera_mp'].isnull()]

Product_Name  Price  Rating  Spec_Score  \
527   Samsung Guru Music 2 Dual Sim    777    4.50          11   
562              Motorola Moto A100    930    4.05           9   
609                         HMD 100    899    4.50           9   
680            HMD 130 Music (2025)   1899    4.55          15   
695             Nokia 220 4G (2024)   3249    4.20          19   
711            Nokia 130 Music 2023   1849    4.20          13   
715         Nokia 105 Dual Sim 2023    984    4.75          10   
718                    Nokia 106 4G   2199    4.20          16   
758               HMD 105 4G (2024)   2199    4.60          17   
823                         HMD 101    999    4.75          11   
828                      HMD 102 4G   1879    4.40          12   
829                      HMD 101 4G   1899    4.75          12   
835              Motorola Moto A200   1149    4.05           9   
875              Motorola Moto A10G    993    4.10          13   
876          Nokia 105 Classic 2023   1049    4.20           7   
886                  Nokia 105 2023   1199    4.70          10   
945                  Philips E2101C   1075    4.40           7   
948                Snexian Bold 40K   1149    4.25          12   
952                   Lava A2 Smart   1079    4.15          11   
959           Lava Hero Shakti 2025    909    4.50          17   
962            HMD 150 Music (2025)   2399    4.00          16   
995                         HMD 105    984    4.70          10   
997                         HMD 110   1164    4.60          12   
1001             Motorola Moto A10V    993    4.00          11   

                                         Specifications  has_dual_sim  has_3g  \
527   Dual Sim | No Wifi | Single Core, 208 MHz Proc...             1       0   
562   Single Sim | Unisoc, 1 MHz Processor | 4 MB RA...             0       0   
609   Dual Sim | Unisoc 6533G | 8 MB RAM, 4 MB inbui...             1       0   
680   Dual Sim | Unisoc 6531F | 8 MB RAM, 8 MB inbui...             1       0   
695   Dual Sim, 3G, 4G | No Wifi | Unisoc T107 | 64 ...             1       1   
711   Dual Sim | No Wifi | 4 MB RAM, 4 MB inbuilt | ...             1       0   
715   Dual Sim | No Wifi | 4 MB RAM, 4 MB inbuilt | ...             1       0   
718   Dual Sim, 3G, 4G, VoLTE | No Wifi | 4 MB RAM |...             1       1   
758   3G, 4G | No Wifi | Unisoc T127 | 128 MB RAM, 6...             0       1   
823   Dual Sim | Unisoc 6533G | 4 MB RAM, 4 MB inbui...             1       0   
828   Dual Sim, 4G | Unisoc 8910 FF-S | 24 MB RAM, 1...             1       0   
829   Dual Sim, 4G | Unisoc 8910 FF-S | 1000 mAh Bat...             1       0   
835   Dual Sim | 56 MB RAM, 36 MB inbuilt | 800 mAh ...             1       0   
875   Dual Sim, 3G | 1.5 MHz Processor | 4 MB RAM, 3...             1       1   
876   Single Sim | 4 MB RAM, 4 MB inbuilt | 800 mAh ...             0       0   
886   Single Sim | No Wifi | 4 MB RAM, 4 MB inbuilt ...             0       0   
945   32 MB RAM, 32 MB inbuilt | 1000 mAh Battery | ...             0       0   
948   Dual Sim | No Wifi | 1 MHz Processor | 32 MB R...             1       0   
952   Dual Sim | Single Core, 1.5 MHz Processor | 4 ...             1       0   
959   Dual Sim | 1.5 MHz Processor | 4 MB RAM, 32 GB...             1       0   
962   Dual Sim | No Wifi | Unisoc 6531F | 8 MB RAM, ...             1       0   
995   Dual Sim | No Wifi | 4 MB RAM, 4 MB inbuilt | ...             1       0   
997   Dual Sim | No Wifi | 4 MB RAM, 4 MB inbuilt | ...             1       0   
1001  Dual Sim | 4 MB RAM, 4 MB inbuilt | 800 mAh Ba...             1       0   

      has_4g  has_5g  has_nfc  ...  display_size_inches resolution_width  \
527        0       0        0  ...                 2.00            128.0   
562        0       0        0  ...                 1.44            240.0   
609        0       0        0  ...                 1.77            160.0   
680        0       0        0  ...        

In [217]:
smartphone_2['card_supported'].value_counts()

card_supported
1.0    794
0.0    225
Name: count, dtype: int64

In [218]:
smartphone_2[smartphone_2['card_supported'] == 0]

Product_Name   Price  Rating  Spec_Score  \
0        Samsung Galaxy S25 Ultra  108460    4.15          93   
1           Samsung Galaxy S25 FE   59999    4.70          86   
8                  OnePlus 15R 5G   47999    4.35          87   
10                 Vivo T4 Pro 5G   27977    4.10          82   
14                Apple iPhone 17   82900    4.60          79   
...                           ...     ...     ...         ...   
993               Lava Blaze X 5G   15999    4.25          76   
996       Samsung Galaxy Z Fold 6  185999    4.25          91   
998       Samsung Galaxy Z Flip 6   74999    4.75          91   
1004                 Realme GT 6T   31999    4.70          85   
1012  Infinix Note 40 Pro Plus 5G   24999    4.15          86   

                                         Specifications  has_dual_sim  has_3g  \
0     Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC ...             1       1   
1     Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC ...             1       1   
8     Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC,...             1       1   
10    Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...             1       1   
14    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC | Appl...             1       1   
...                                                 ...           ...     ...   
993   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi | Dimensity...             1       1   
996   Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC ...             1       1   
998   Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC ...             1       1   
1004  Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC,...             1       1   
1012  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...             1       1   

      has_4g  has_5g  has_nfc  ...  display_size_inches resolution_width  \
0          1       1        1  ...                 6.90           1440.0   
1          1       1        1  ...                 6.70           1080.0   
8          1       1        1  ...                 6.83           1272.0   
10         1       1        0  ...                 6.77           1080.0   
14         1       1        1  ...                 6.30           1206.0   
...      ...     ...      ...  ...                  ...              ...   
993        1       1        0  ...                 6.67           1080.0   
996        1       1        1  ...                 7.60           1856.0   
998        1       1        1  ...                 6.70           1080.0   
1004       1       1        1  ...                 6.78           1264.0   
1012       1       1        1  ...                 6.78           1080.0   

     resolution_height  display_frequency_hz  front_camera_mp  rear_camera_mp  \
0               3120.0                 120.0             12.0           200.0   
1               2340.0                 120.0             12.0            50.0   
8               2800.0                 165.0             32.0            50.0   
10              2392.0                 120.0             32.0            50.0   
14              2622.0                 120.0             18.0            48.0   
...                ...                   ...              ...             ...   
993             2400.0                 120.0             16.0            64.0   
996             2160.0                 120.0              NaN            50.0   
998             2640.0                 120.0             10.0            50.0   
1004            2780.0                 120.0             32.0            50.0   
1012            2436.0                 120.0             32.0           108.0   

      card_supported  operating_system  \
0                0.0       Android v15   
1                0.0       Android v16   
8                0.0       Android v16   
10               0.0       Android v15   
14               0.0           iOS v26   
...              ...               ...   
993              0.0       Android v14   
996              0.0               NaN   
998

In [219]:
smartphone_2['operating_system'].value_counts()

operating_system
Android v15       347
Android v14       309
Android v13        98
Android v12        56
Android v11        34
Android v16        30
iOS v18            16
iOS v26            12
Android v10         7
iOS v17             4
iOS v16             3
Android v9.0        3
Android v10.0       3
Android v6.0.1      2
Android v13.0       2
Android v8.1        2
Android v14.0       2
iOS v15             1
Android             1
iOS v2.5.3          1
Android v6.0        1
iOS v13             1
Android v7.1.2      1
Android v10.1       1
Name: count, dtype: int64

In [220]:
smartphone_2[smartphone_2['operating_system'].isnull()]

Product_Name  Price  Rating  Spec_Score  \
344      Peace Nova 17 Pro 4G   7999    4.55          51   
366            Lava Agni 3 5G  16499    4.40          81   
391              HMD Touch 4G   3999    4.55          26   
437          Jio Bharat J1 4G   1799    4.35          23   
445    itel Super Guru 4G Max   2399    4.10          15   
...                       ...    ...     ...         ...   
997                   HMD 110   1164    4.60          12   
998   Samsung Galaxy Z Flip 6  74999    4.75          91   
1001       Motorola Moto A10V    993    4.00          11   
1002       Motorola Moto A50V   1111    4.75          13   
1019              itel it5330   1663    4.45          14   

                                         Specifications  has_dual_sim  has_3g  \
344   Dual Sim, 3G, 4G, VoLTE, Wi-Fi | MTK6739, Sing...             1       1   
366   Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi | Dim...             1       1   
391   Dual Sim, 3G, 4G, Wi-Fi | Unisoc T127 | 128 MB...             1       1   
437   Single Sim, 3G, 4G, VoLTE | 512 MB RAM, 4 GB i...             0       1   
445   Dual Sim, 3G, 4G, VoLTE | 64 MB RAM | 2000 mAh...             1       1   
...                                                 ...           ...     ...   
997   Dual Sim | No Wifi | 4 MB RAM, 4 MB inbuilt | ...             1       0   
998   Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC ...             1       1   
1001  Dual Sim | 4 MB RAM, 4 MB inbuilt | 800 mAh Ba...             1       0   
1002  Dual Sim | 4 MB RAM, 4 MB inbuilt | 1750 mAh B...             1       0   
1019  Dual Sim | 32 MB RAM, 32 MB inbuilt | 1900 mAh...             1       0   

      has_4g  has_5g  has_nfc  ...  display_size_inches resolution_width  \
344        1       0        0  ...                 6.56           1640.0   
366        1       1        0  ...                 6.78           1200.0   
391        1       0        0  ...                 3.20            240.0   
437        1       0        0  ...                 2.80            240.0   
445        1       0        0  ...                 3.00              NaN   
...      ...     ...      ...  ...                  ...              ...   
997        0       0        0  ...                 2.00            120.0   
998        1       1        1  ...                 6.70           1080.0   
1001       0       0        0  ...                 1.80            160.0   
1002       0       0        0  ...                 1.80            160.0   
1019       0       0        0  ...                 2.80            320.0   

     resolution_height  display_frequency_hz  front_camera_mp  rear_camera_mp  \
344              720.0                   NaN              8.0            20.0   
366             2652.0                 120.0             16.0            50.0   
391              320.0                   NaN              NaN             2.0   
437              320.0                   NaN              NaN             3.0   
445                NaN                   NaN              NaN             3.0   
...                ...                   ...              ...             ...   
997              160.0                   NaN              NaN             NaN   
998             2640.0                 120.0             10.0            50.0   
1001             128.0                   NaN              NaN             NaN   
1002             128.0                   NaN              NaN             3.0   
1019             240.0                   NaN              NaN             3.0   

      card_supported  operating_system  \
344              1.0               NaN   
366              0.0               NaN   
391              1.0               NaN   
437              1.0               NaN   
445              1.0               NaN   
...              ...               ...   
997              1.0               NaN   
998              0.0               NaN   
1001             1.0               NaN   
1002             

In [221]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

smartphone_2[smartphone_2['processor_name'].isnull()]

Product_Name  Price  Rating  Spec_Score  \
209                 Google Pixel 8A  39999    4.65          76   
353               Google Pixel 8 5G  38999    4.50          75   
391                    HMD Touch 4G   3999    4.55          26   
404         Jio JioPhone Prima 2 4G   2799    4.35          24   
437                Jio Bharat J1 4G   1799    4.35          23   
445          itel Super Guru 4G Max   2399    4.10          15   
448                 iKall I1 Pro 4G   2999    4.45          35   
461              Google Pixel 8 Pro  79999    4.70          79   
517               Nokia 235 4G 2024   3749    4.10          20   
527   Samsung Guru Music 2 Dual Sim    777    4.50          11   
540                Jio Bharat V4 4G    789    4.40          22   
558               Samsung Metro 313    982    4.50          14   
562              Motorola Moto A100    930    4.05           9   
609                         HMD 100    899    4.50           9   
637            Nokia 3210 4G (2024)   3999    4.25          20   
664                Peace Nova 11 4G   5899    4.65          42   
665               iKall Z10 4G 2025   6449    4.00          61   
678                  Lava Action 4G   1799    4.45          17   
680            HMD 130 Music (2025)   1899    4.55          15   
684          BlackZone WINX 4G Plus   3299    4.25          42   
686                   Jio Bharat V3    799    4.75          22   
695             Nokia 220 4G (2024)   3249    4.20          19   
711            Nokia 130 Music 2023   1849    4.20          13   
714           Jio Bharat K1 Karbonn    890    4.40          21   
715         Nokia 105 Dual Sim 2023    984    4.75          10   
718                    Nokia 106 4G   2199    4.20          16   
758               HMD 105 4G (2024)   2199    4.60          17   
822                        Gamma W5   1849    4.45          16   
823                         HMD 101    999    4.75          11   
824                     MTR M16 Pro   4600    4.30          29   
828                      HMD 102 4G   1879    4.40          12   
829                      HMD 101 4G   1899    4.75          12   
832                   Philips E2102   1234    4.70           7   
835              Motorola Moto A200   1149    4.05           9   
857               Nokia 6310 (2024)   3499    4.20          16   
876          Nokia 105 Classic 2023   1049    4.20           7   
883                   Jio Bharat V2    990    4.50          22   
886                  Nokia 105 2023   1199    4.70          10   
941                     GFive A51-C    799    4.15          14   
943                         MTR M15   4600    4.10          28   
945                  Philips E2101C   1075    4.40           7   
950                 Snexian Guru 30    899    4.00          15   
952                   Lava A2 Smart   1079    4.15          11   
962            HMD 150 Music (2025)   2399    4.00          16   
966              Lava A7 Torch Plus   1444    4.30          15   
968                      Amaq Q1 4G   2789    4.25          19   
970            iKall K99 Pro Rugged   1349    4.10          15   
974         Micromax X1i Smart Plus    999    4.30          12   
995                         HMD 105    984    4.70          10   
997                         HMD 110   1164    4.60          12   
1001             Motorola Moto A10V    993    4.00          11   
1002             Motorola Moto A50V   1111    4.75          13   
1019                    itel it5330   1663    4.45          14   

                                                                                                                                                                                                                                                                                                  Specifications  \
209      Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC | Tensor G3, Nine-Cores, 3 GHz Processor | 8 GB RAM, 128 GB inbuilt | 4492 mAh Battery with Fast Char

In [222]:
pd.reset_option('display.max_columns')
pd.reset_option('display.max_rows')
pd.reset_option('display.max_colwidth')

In [223]:
smartphone_2['has_dual_sim'].value_counts()

has_dual_sim
1    1003
0      16
Name: count, dtype: int64

In [224]:
smartphone_2['has_3g'].value_counts()

has_3g
1    978
0     41
Name: count, dtype: int64

In [225]:
smartphone_2['has_5g'].value_counts()

has_5g
1    838
0    181
Name: count, dtype: int64

Based on my analysis of your cleaned dataset, here's a **comprehensive, organized list of ALL quality issues** you have (including ones you missed):[1]

***

## **Complete Data Quality Issues - Organized by Column**

### **Product_Name**
✅ **No issues** - Successfully cleaned[1]

***

### **Price** 
✅ **No issues** - Successfully cleaned[1]

***

### **Rating**
✅ **No issues**[1]

***

### **Spec_Score**
✅ **No issues** - Successfully cleaned[1]

***

### **processor_name** (53 missing values)

1. **Consistency**: "Snapdragon 8 Elite for Galaxy" should be "Snapdragon 8 Elite" (6 phones)[1]

2. **Validity**: Wrong processor names - MHz/Hz values appearing as processor:
   - 13 phones total with MHz/Hz as processor names
   - Indices: 494, 663, 676, 768, 875, 942, 944, 948, 949, 959
   - Values: '1.5 MHz', '256 MHz', '512 MHz', '1 MHz', '5 MHz'[1]

3. **Completeness**: Problematic processor names not captured by regex:
   - Unisoc T127 (2 phones) - in specs but not extracted
   - MTK MT6739 (1 phone) - in specs but not extracted
   - Unisoc T107 (3 phones) - in specs but not extracted
   - Unisoc 6533G (2 phones) - in specs but not extracted
   - Helio 6739 (1 phone) - in specs but not extracted
   - Unisoc 6531F (3 phones) - in specs but not extracted[1]

4. **Completeness**: Keypad phones (77 total) - 42 missing processor names[1]

***

### **cores** (58 missing values)

5. **Completeness**: "Nine Core" not recognized by regex (2 phones at indices 353, 461)[1]

6. **Completeness**: Keypad phones - many missing core values[1]

***

### **cpu_speed_ghz** (106 missing values)

7. **Validity**: MHz values in specifications not converted to GHz:
   - 1.3 MHz, 1.5 MHz, 1.77 MHz, 5 MHz, 208 MHz, 512 MHz[1]

8. **Completeness**: Apple phones (37 total) - 12 missing CPU speed (32%)[1]

9. **Completeness**: Realme phones (144 total) - 11 missing CPU speed (7.6%)[1]

10. **Completeness**: Google phones (19 total) - 1 missing CPU speed[1]

11. **Completeness**: OPPO phones (80 total) - 1 missing CPU speed[1]

***

### **ram_gb** (59 missing values)

12. **Validity**: **52 phones with MB RAM** instead of GB - completely not extracted (e.g., 128 MB, 4 MB, 32 MB RAM)[1]

13. **Completeness**: Apple phones - 3 missing RAM values (indices: 128, 322, 844)[1]

14. **Completeness**: Keypad phones - 50 missing RAM values[1]

***

### **rom_gb** (61 missing values)

15. **Validity/Tidiness**: **10 phones with 1 TB storage** - values are NaN instead of 1000 GB (indices: 268, 319, 450, 465, 694, etc.)[1]

16. **Validity**: **44 phones with MB ROM** instead of GB - not extracted (e.g., 32 MB, 64 MB storage)[1]

17. **Completeness**: Keypad phones - 45 missing ROM values[1]

***

### **battery_capacity_mah**
✅ **No issues** - Successfully extracted[1]

***

### **fast_charging_available**
✅ **No issues**[1]

***

### **fast_charging_speed_w** (132 missing values)

18. **Completeness**: **Apple phones (36 phones)** - have fast_charging_available=1 but missing wattage[1]

19. **Tidiness**: **79 phones** where fast_charging_available=0 should have fast_charging_speed_w=0 (not NaN)[1]

***

### **display_size_inches**
✅ **No issues** - Successfully extracted[1]

***

### **resolution_width / resolution_height** (9 missing each)

20. **Validity**: **9 phones** with display size but no "px" in specs - resolution not extracted:
   - Indices: 445, 664, 828, 829, 832
   - Specs show: "3 inches Display", "6.56 inches Display", "2 inches Display" (no resolution in px format)[1]

21. **Tidiness**: Data type should be int, currently float64[1]

***

### **display_frequency_hz** (151 missing values)

22. **Completeness**: **151 phones** with display but no refresh rate in specifications[1]

23. **Completeness**: **Apple phones (20 phones)** - missing display frequency[1]

***

### **front_camera_mp** (95 missing values)

24. **Validity**: **38 phones** with decimal MP values (e.g., 10.5 MP) - not extracted by regex[1]

25. **Validity**: **22 phones** with "Dual Front Camera" or "Triple Front Camera" - not extracted (indices: 56, 105, 236, 255, 268, etc.)[1]

26. **Completeness**: Keypad phones - 55 missing front camera values[1]

***

### **rear_camera_mp** (24 missing values)

27. **Validity**: **20 phones** with "No Rear Camera" - should be filled with 0 (currently NaN)[1]

28. **Tidiness**: **877 phones** have multiple rear cameras (Dual/Triple/Quad) - only primary MP stored, loses camera count information[1]

29. **Completeness**: Keypad phones - 23 missing rear camera values[1]

***

### **card_supported**

30. **Tidiness**: Data type is float64, should be int (0/1)[1]

***

### **operating_system** (82 missing values)

31. **Consistency**: **18 phones** have OS with decimal precision (e.g., "Android v10.1", "iOS v2.5.3") - should normalize to integer (Android v10, iOS v2)[1]

32. **Completeness**: **5 phones** with Symbian OS in specs - not extracted (indices: 941, 944, 948, 949, 950)[1]

33. **Completeness**: **82 phones** (mostly keypad/feature phones) with missing OS - leave blank for model building team to handle[1]

***

## **Additional Issues You Missed:**

### **Tidiness Issue (You Mentioned)**

35. **Tidiness**: **Dual front camera column** - Need second column for secondary front camera MP (fill 0 if single camera)[1]

***

### **Data Type Issues**

36. **Tidiness**: **resolution_width/height** should be int, currently float[1]

37. **Tidiness**: **card_supported** should be int, currently float[1]

***

### **Structural Issues**


38.  **Accuracy**: **48 phones** missing BOTH ram_gb AND rom_gb - may indicate data quality issues[1]

***

### **Keypad/Feature Phones Category**

39. **Completeness**: **77 keypad/feature phones** identified (no Android/iOS/Windows) with extensive missing features - this is expected behavior[1]

***

## **Summary Statistics:**[1]
- Total rows: 1,020
- Columns: 29
- Major missing value columns: display_frequency_hz (151), fast_charging_speed_w (132), cpu_speed_ghz (106), front_camera_mp (95), operating_system (82)

## **Recommendation for Question 31:**
**Yes, leave blank OS values as-is.** Your job is data cleaning, not imputation. Document that 82 phones (mostly keypad/feature phones without Android/iOS) have no OS information available in the source data. The model building team will decide on imputation strategies (e.g., create "Feature Phone" category, drop rows, etc.).[1]

[1](https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/attachments/20925570/81938600-ec87-4365-b065-583eeeb9c2b6/smartprix_mobiles_cleaned.csv)
[2](https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/attachments/20925570/649f0eee-8173-4520-8539-ab3c5352cf74/smartprix_mobiles.csv)

## <center> <b> 2nd iteration of Data Cleaning

In [226]:
# Problem 1: Remove "for Galaxy" from Snapdragon 8 Elite processor names

# Load cleaned data
df = pd.read_csv('smartprix_mobiles_cleaned.csv')

print("Before fixing:")
print(df[df['processor_name'].str.contains('for Galaxy',
      case=False, na=False)]['processor_name'].unique())

# Fix the processor name
df['processor_name'] = df['processor_name'].str.replace(
    r'\s*for\s+Galaxy', '', case=False, regex=True)

print("\nAfter fixing:")
print(df[df['processor_name'].str.contains('Snapdragon 8 Elite',
      case=False, na=False)]['processor_name'].unique())
print(f"✓ Fixed 'for Galaxy' issue")

Before fixing:
['Snapdragon 8 Elite for Galaxy']

After fixing:
['Snapdragon 8 Elite' 'Snapdragon 8 Elite Gen 5']
✓ Fixed 'for Galaxy' issue


In [227]:
# Problem 2-3: Fix wrong processor names (MHz/Hz values)

print("Processors with MHz/Hz:")
mhz_processors = df[df['processor_name'].str.contains(
    r'MHz|Hz', case=False, na=False, regex=True)]
print(f"Count: {len(mhz_processors)}")
print(f"Indices: {mhz_processors.index.tolist()}")
print(f"Values: {mhz_processors['processor_name'].unique()}")

# Strategy: Extract processor name from Specifications for these rows


def extract_processor_from_spec(spec_text):
    """Extract processor name more carefully"""
    if pd.isna(spec_text):
        return np.nan

    # Split by pipe
    parts = str(spec_text).split('|')
    if len(parts) < 2:
        return np.nan

    processor_part = parts[1].strip()

    # Remove "Processor" word
    processor_part = processor_part.replace('Processor', '').strip()

    # Remove core info and GHz info
    # Extract everything before comma or "Core"
    import re
    match = re.search(
        r'^([^,]+?)(?:,|\s+(?:Octa|Quad|Hexa|Deca|Dual|Single)\s*Core)', processor_part, re.IGNORECASE)
    if match:
        return match.group(1).strip()

    # If no match, return the first part before comma
    if ',' in processor_part:
        return processor_part.split(',')[0].strip()

    return processor_part


# Fix rows with MHz/Hz in processor name
for idx in mhz_processors.index:
    spec = df.loc[idx, 'Specifications']
    new_processor = extract_processor_from_spec(spec)

    # If the new processor still has MHz, set to NaN
    if pd.notna(new_processor) and ('MHz' in new_processor or 'Hz' in new_processor):
        df.loc[idx, 'processor_name'] = np.nan
    else:
        df.loc[idx, 'processor_name'] = new_processor

print("\n✓ Fixed MHz/Hz in processor names")
print(
    f"After fix, remaining MHz/Hz processors: {df['processor_name'].str.contains('MHz|Hz', case=False, na=False, regex=True).sum()}")

Processors with MHz/Hz:
Count: 13
Indices: [494, 663, 676, 768, 875, 942, 944, 948, 949, 959, 961, 989, 990]
Values: ['1.5 MHz' '256 MHz' '512 MHz' '1 MHz' '5 MHz' '1.3 MHz' '1.77 MHz']

✓ Fixed MHz/Hz in processor names
After fix, remaining MHz/Hz processors: 0


In [228]:
# Problem 3: Extract problematic processor names (Unisoc, MTK, Helio, etc.)

# List of processor patterns to look for
processor_patterns = [
    'Unisoc T127', 'Unisoc T107', 'Unisoc 6533G', 'Unisoc 6531F',
    'MTK MT6739', 'MTK6739', 'Helio 6739', 'AMD'
]

print("Extracting missing processor names...")

for pattern in processor_patterns:
    # Find phones with this processor in specs
    has_pattern = df['Specifications'].str.contains(
        pattern, case=False, na=False, regex=False)

    # Check if processor_name is missing or doesn't contain the pattern
    needs_fix = has_pattern & (df['processor_name'].isna() |
                               ~df['processor_name'].str.contains(pattern, case=False, na=False, regex=False))

    if needs_fix.sum() > 0:
        print(f"\n{pattern}: {needs_fix.sum()} phones need fixing")
        print(f"  Indices: {df[needs_fix].index.tolist()}")

        # Set the processor name
        df.loc[needs_fix, 'processor_name'] = pattern

print("\n✓ Extracted problematic processor names")

Extracting missing processor names...

Unisoc T127: 2 phones need fixing
  Indices: [391, 758]

Unisoc T107: 3 phones need fixing
  Indices: [517, 637, 695]

Unisoc 6533G: 2 phones need fixing
  Indices: [609, 823]

Unisoc 6531F: 3 phones need fixing
  Indices: [680, 857, 962]

MTK MT6739: 1 phones need fixing
  Indices: [448]

Helio 6739: 1 phones need fixing
  Indices: [664]

✓ Extracted problematic processor names


In [229]:
# Problem 5: Add "Nine Core" to cores extraction

print("Checking Nine Core processors...")

# Find phones with Nine Core in specifications
nine_core_specs = df['Specifications'].str.contains(
    r'Nine\s*Core', case=False, na=False, regex=True)

if nine_core_specs.sum() > 0:
    print(f"Found {nine_core_specs.sum()} phones with Nine Core in specs")
    print(f"Indices: {df[nine_core_specs].index.tolist()}")

    # Fix cores column
    for idx in df[nine_core_specs].index:
        df.loc[idx, 'cores'] = 'Nine Core'

    print("✓ Fixed Nine Core in cores column")
else:
    print("No Nine Core processors found")

Checking Nine Core processors...
Found 2 phones with Nine Core in specs
Indices: [353, 461]
✓ Fixed Nine Core in cores column


In [230]:
# Problem 7: Convert MHz values to GHz in specifications

import re
print("Checking for MHz values in specifications that should be GHz...")

# Find phones with MHz in specs (not GHz)
mhz_in_specs = df['Specifications'].str.contains(
    r'\d+\.?\d*\s*MHz', case=False, na=False, regex=True)
print(f"Phones with MHz in specs: {mhz_in_specs.sum()}")

# Extract MHz values and convert to GHz

for idx in df[mhz_in_specs].index:
    spec = df.loc[idx, 'Specifications']

    # Look for MHz values
    mhz_match = re.search(r'(\d+\.?\d*)\s*MHz', spec, re.IGNORECASE)

    if mhz_match and pd.isna(df.loc[idx, 'cpu_speed_ghz']):
        mhz_value = float(mhz_match.group(1))

        # Convert MHz to GHz
        ghz_value = mhz_value / 1000

        df.loc[idx, 'cpu_speed_ghz'] = ghz_value
        print(f"  Index {idx}: Converted {mhz_value} MHz to {ghz_value} GHz")

print("\n✓ Converted MHz to GHz")

Checking for MHz values in specifications that should be GHz...
Phones with MHz in specs: 29
  Index 390: Converted 1.3 MHz to 0.0013 GHz
  Index 448: Converted 512.0 MHz to 0.512 GHz
  Index 494: Converted 1.5 MHz to 0.0015 GHz
  Index 527: Converted 208.0 MHz to 0.208 GHz
  Index 558: Converted 208.0 MHz to 0.208 GHz
  Index 562: Converted 1.0 MHz to 0.001 GHz
  Index 610: Converted 1.3 MHz to 0.0013 GHz
  Index 663: Converted 256.0 MHz to 0.256 GHz
  Index 676: Converted 512.0 MHz to 0.512 GHz
  Index 737: Converted 1.3 MHz to 0.0013 GHz
  Index 768: Converted 1.0 MHz to 0.001 GHz
  Index 822: Converted 1.2 MHz to 0.0012 GHz
  Index 824: Converted 512.0 MHz to 0.512 GHz
  Index 825: Converted 1.3 MHz to 0.0013 GHz
  Index 827: Converted 1.3 MHz to 0.0013 GHz
  Index 875: Converted 1.5 MHz to 0.0015 GHz
  Index 941: Converted 1.2 MHz to 0.0012 GHz
  Index 942: Converted 5.0 MHz to 0.005 GHz
  Index 943: Converted 512.0 MHz to 0.512 GHz
  Index 944: Converted 1.3 MHz to 0.0013 GHz
  I

In [231]:
# Problems 8-11: Document missing CPU speeds for certain brands
# Note: These phones genuinely don't have CPU speed in specifications
# This is expected and not an error

print("=== CPU Speed Missing by Brand (Expected) ===")

brands_check = {
    'Apple|iPhone': 'Apple',
    'Realme': 'Realme',
    'Google|Pixel': 'Google',
    'OPPO|Oppo': 'OPPO'
}

for pattern, brand_name in brands_check.items():
    brand_phones = df[df['Product_Name'].str.contains(
        pattern, case=False, na=False, regex=True)]
    missing_cpu = brand_phones[brand_phones['cpu_speed_ghz'].isna()]

    print(f"\n{brand_name}:")
    print(f"  Total phones: {len(brand_phones)}")
    print(
        f"  Missing CPU speed: {len(missing_cpu)} ({len(missing_cpu)/len(brand_phones)*100:.1f}%)")

print("\n✓ This is expected - these brands don't publish CPU speeds in specs")
print("✓ No action needed - leave as NaN")

=== CPU Speed Missing by Brand (Expected) ===

Apple:
  Total phones: 37
  Missing CPU speed: 12 (32.4%)

Realme:
  Total phones: 144
  Missing CPU speed: 11 (7.6%)

Google:
  Total phones: 19
  Missing CPU speed: 1 (5.3%)

OPPO:
  Total phones: 80
  Missing CPU speed: 1 (1.2%)

✓ This is expected - these brands don't publish CPU speeds in specs
✓ No action needed - leave as NaN


In [232]:
# Problem 12: Extract RAM values in MB and convert to GB

print("Extracting RAM values in MB...")

# Find phones with MB RAM in specs but missing ram_gb
mb_ram_specs = df['Specifications'].str.contains(
    r'\d+\s*MB\s*RAM', case=False, na=False, regex=True)
missing_ram = df['ram_gb'].isna()

needs_mb_extraction = mb_ram_specs & missing_ram

print(f"Phones with MB RAM to extract: {needs_mb_extraction.sum()}")

if needs_mb_extraction.sum() > 0:
    import re

    for idx in df[needs_mb_extraction].index:
        spec = df.loc[idx, 'Specifications']

        # Extract MB value
        mb_match = re.search(r'(\d+)\s*MB\s*RAM', spec, re.IGNORECASE)

        if mb_match:
            mb_value = int(mb_match.group(1))
            gb_value = mb_value / 1024  # Convert MB to GB

            df.loc[idx, 'ram_gb'] = round(gb_value, 3)

            if idx < 10 or idx % 10 == 0:  # Show sample outputs
                print(f"  Index {idx}: {mb_value} MB = {gb_value:.3f} GB")

print(
    f"\n✓ Extracted and converted {needs_mb_extraction.sum()} RAM values from MB to GB")

Extracting RAM values in MB...
Phones with MB RAM to extract: 52
  Index 540: 512 MB = 0.500 GB
  Index 680: 8 MB = 0.008 GB
  Index 950: 32 MB = 0.031 GB
  Index 970: 32 MB = 0.031 GB
  Index 990: 32 MB = 0.031 GB

✓ Extracted and converted 52 RAM values from MB to GB


In [233]:
# Problem 13: Document Apple phones missing RAM
# Note: Apple doesn't publish RAM specs, this is expected

print("=== Apple Phones Missing RAM (Expected) ===")

apple_phones = df[df['Product_Name'].str.contains(
    'Apple|iPhone', case=False, na=False, regex=True)]
apple_no_ram = apple_phones[apple_phones['ram_gb'].isna()]

print(f"Apple phones: {len(apple_phones)}")
print(
    f"Missing RAM: {len(apple_no_ram)} ({len(apple_no_ram)/len(apple_phones)*100:.1f}%)")

if len(apple_no_ram) > 0:
    print(f"Indices: {apple_no_ram.index.tolist()}")

print("\n✓ This is expected - Apple doesn't publish RAM in specs")
print("✓ No action needed - leave as NaN")

=== Apple Phones Missing RAM (Expected) ===
Apple phones: 37
Missing RAM: 3 (8.1%)
Indices: [128, 322, 844]

✓ This is expected - Apple doesn't publish RAM in specs
✓ No action needed - leave as NaN


In [234]:
# Problem 15: Extract ROM values in TB and convert to GB (1 TB = 1000 GB)

print("Extracting ROM values in TB...")

# Find phones with TB storage in specs
tb_rom_specs = df['Specifications'].str.contains(r'(\d+)\s*TB\s*(?:inbuilt|internal)',
                                                 case=False, na=False, regex=True)

print(f"Phones with TB storage: {tb_rom_specs.sum()}")

if tb_rom_specs.sum() > 0:
    import re

    for idx in df[tb_rom_specs].index:
        spec = df.loc[idx, 'Specifications']

        # Extract TB value
        tb_match = re.search(
            r'(\d+)\s*TB\s*(?:inbuilt|internal)', spec, re.IGNORECASE)

        if tb_match:
            tb_value = int(tb_match.group(1))
            gb_value = tb_value * 1000  # Convert TB to GB

            df.loc[idx, 'rom_gb'] = gb_value
            print(f"  Index {idx}: {tb_value} TB = {gb_value} GB")

print(
    f"\n✓ Extracted and converted {tb_rom_specs.sum()} ROM values from TB to GB")

Extracting ROM values in TB...
Phones with TB storage: 11
  Index 268: 1 TB = 1000 GB
  Index 291: 2 TB = 2000 GB
  Index 319: 1 TB = 1000 GB
  Index 450: 1 TB = 1000 GB
  Index 465: 1 TB = 1000 GB
  Index 694: 1 TB = 1000 GB
  Index 741: 1 TB = 1000 GB
  Index 742: 1 TB = 1000 GB
  Index 759: 1 TB = 1000 GB
  Index 978: 1 TB = 1000 GB
  Index 996: 1 TB = 1000 GB

✓ Extracted and converted 11 ROM values from TB to GB


C:\Users\Lappy\AppData\Local\Temp\ipykernel_768\593739016.py:6: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  tb_rom_specs = df['Specifications'].str.contains(r'(\d+)\s*TB\s*(?:inbuilt|internal)',


In [235]:
# Problem 16: Extract ROM values in MB and convert to GB

print("Extracting ROM values in MB...")

# Find phones with MB ROM in specs but missing rom_gb
mb_rom_specs = df['Specifications'].str.contains(r'\d+\s*MB\s*(?:inbuilt|internal)',
                                                 case=False, na=False, regex=True)
missing_rom = df['rom_gb'].isna()

needs_mb_rom_extraction = mb_rom_specs & missing_rom

print(f"Phones with MB ROM to extract: {needs_mb_rom_extraction.sum()}")

if needs_mb_rom_extraction.sum() > 0:
    import re

    for idx in df[needs_mb_rom_extraction].index:
        spec = df.loc[idx, 'Specifications']

        # Extract MB value
        mb_match = re.search(
            r'(\d+)\s*MB\s*(?:inbuilt|internal)', spec, re.IGNORECASE)

        if mb_match:
            mb_value = int(mb_match.group(1))
            gb_value = mb_value / 1024  # Convert MB to GB

            df.loc[idx, 'rom_gb'] = round(gb_value, 3)

            if idx < 10 or idx % 10 == 0:  # Show sample outputs
                print(f"  Index {idx}: {mb_value} MB = {gb_value:.3f} GB")

print(
    f"\n✓ Extracted and converted {needs_mb_rom_extraction.sum()} ROM values from MB to GB")

Extracting ROM values in MB...
Phones with MB ROM to extract: 44
  Index 680: 8 MB = 0.008 GB
  Index 950: 32 MB = 0.031 GB
  Index 970: 32 MB = 0.031 GB
  Index 990: 32 MB = 0.031 GB

✓ Extracted and converted 44 ROM values from MB to GB


In [236]:
# Problem 18: Apple phones with fast charging but no wattage
# Note: Apple doesn't publish wattage, this is expected

print("=== Apple Phones Fast Charging (Expected Missing) ===")

apple_phones = df[df['Product_Name'].str.contains(
    'Apple|iPhone', case=False, na=False, regex=True)]
apple_fast = apple_phones[(apple_phones['fast_charging_available'] == 1) &
                          (apple_phones['fast_charging_speed_w'].isna())]

print(f"Apple phones with fast charging: {len(apple_fast)}")
print(f"Missing wattage: {len(apple_fast)} (all of them)")

print("\n✓ This is expected - Apple doesn't publish fast charging wattage")
print("✓ No action needed - leave as NaN")
print("✓ Model building team can impute typical Apple fast charging values if needed")

=== Apple Phones Fast Charging (Expected Missing) ===
Apple phones with fast charging: 36
Missing wattage: 36 (all of them)

✓ This is expected - Apple doesn't publish fast charging wattage
✓ No action needed - leave as NaN
✓ Model building team can impute typical Apple fast charging values if needed


In [237]:
# Problem 19: Fill 0 for fast_charging_speed_w when no fast charging

print("Filling 0 for phones without fast charging...")

# Find phones where fast_charging_available=0 and speed is NaN
no_fast_charging = (df['fast_charging_available'] == 0) & (
    df['fast_charging_speed_w'].isna())

print(
    f"Phones with fast_charging_available=0 and speed=NaN: {no_fast_charging.sum()}")

# Fill with 0
df.loc[no_fast_charging, 'fast_charging_speed_w'] = 0.0

print(
    f"✓ Filled {no_fast_charging.sum()} rows with 0 for fast_charging_speed_w")

# Verify
verify = (df['fast_charging_available'] == 0) & (
    df['fast_charging_speed_w'].isna())
print(f"Remaining NaN with fast_charging_available=0: {verify.sum()}")

Filling 0 for phones without fast charging...
Phones with fast_charging_available=0 and speed=NaN: 79
✓ Filled 79 rows with 0 for fast_charging_speed_w
Remaining NaN with fast_charging_available=0: 0


In [238]:
# Problem 20: Phones with display but no resolution (no "px" in specs)
# These phones genuinely don't have resolution in specifications

print("=== Phones with Display but No Resolution ===")

has_display = df['display_size_inches'].notna()
missing_resolution = (df['resolution_width'].isna()) | (
    df['resolution_height'].isna())
display_no_res = df[has_display & missing_resolution]

print(f"Phones with display size but no resolution: {len(display_no_res)}")
print(f"Indices: {display_no_res.index.tolist()}")

if len(display_no_res) > 0:
    print("\nSample specifications:")
    for idx in display_no_res.index[:3]:
        spec = df.loc[idx, 'Specifications']
        for part in spec.split('|'):
            if 'Display' in part or 'inches' in part:
                print(f"  Index {idx}: {part.strip()}")

print("\n✓ These phones don't have resolution in 'width x height px' format in specs")
print("✓ No action needed - leave as NaN (data not available in source)")

=== Phones with Display but No Resolution ===
Phones with display size but no resolution: 9
Indices: [445, 664, 828, 829, 832, 888, 942, 945, 968]

Sample specifications:
  Index 445: 3 inches Display
  Index 664: 6.56 inches Display
  Index 828: 2 inches Display

✓ These phones don't have resolution in 'width x height px' format in specs
✓ No action needed - leave as NaN (data not available in source)


In [239]:
# Problem 24: Document phones missing display frequency
# Note: 151 phones genuinely don't have Hz in specifications

print("=== Missing Display Frequency (Expected) ===")

has_display = df['display_size_inches'].notna()
missing_freq = df['display_frequency_hz'].isna()
display_no_freq = df[has_display & missing_freq]

print(f"Phones with display but no frequency: {len(display_no_freq)}")

# Check Apple phones specifically
apple_no_freq = df[df['Product_Name'].str.contains('Apple|iPhone', case=False, na=False) &
                   df['display_frequency_hz'].isna()]
print(f"Apple phones missing display frequency: {len(apple_no_freq)}")

print("\n✓ This is expected - many phones don't have refresh rate in specs")
print("✓ No action needed - leave as NaN")

=== Missing Display Frequency (Expected) ===
Phones with display but no frequency: 151
Apple phones missing display frequency: 20

✓ This is expected - many phones don't have refresh rate in specs
✓ No action needed - leave as NaN


In [240]:
# Problem 25: Extract front camera with decimal MP values (e.g., 10.5 MP)

import re
print("Extracting front camera with decimal MP values...")

# Find phones with decimal MP in front camera specs

decimal_front = df['Specifications'].str.contains(r'\d+\.\d+\s*MP.*Front',
                                                  case=False, na=False, regex=True)
missing_front = df['front_camera_mp'].isna()

needs_decimal_extraction = decimal_front & missing_front

print(
    f"Phones with decimal front camera MP to extract: {needs_decimal_extraction.sum()}")

if needs_decimal_extraction.sum() > 0:
    for idx in df[needs_decimal_extraction].index:
        spec = df.loc[idx, 'Specifications']

        # Extract decimal MP value for front camera
        # Pattern: number (with decimal) + MP + ... + Front
        front_match = re.search(
            r'&\s*(\d+\.?\d*)\s*MP\s*Front', spec, re.IGNORECASE)

        if front_match:
            mp_value = float(front_match.group(1))
            df.loc[idx, 'front_camera_mp'] = mp_value

            if idx % 10 == 0:  # Show sample outputs
                print(f"  Index {idx}: Extracted {mp_value} MP")

print(
    f"\n✓ Extracted {needs_decimal_extraction.sum()} decimal front camera values")

Extracting front camera with decimal MP values...
Phones with decimal front camera MP to extract: 13

✓ Extracted 13 decimal front camera values


In [241]:
# Problem 26: Extract front camera when "Dual/Triple Front Camera" is mentioned

print("Extracting Dual/Triple Front Camera values...")

# Find phones with Dual/Triple Front Camera
dual_front = df['Specifications'].str.contains(r'(Dual|Triple)\s+Front\s*Camera',
                                               case=False, na=False, regex=True)
missing_front = df['front_camera_mp'].isna()

needs_dual_extraction = dual_front & missing_front

print(
    f"Phones with Dual/Triple Front Camera to extract: {needs_dual_extraction.sum()}")

if needs_dual_extraction.sum() > 0:
    for idx in df[needs_dual_extraction].index:
        spec = df.loc[idx, 'Specifications']

        # Look for MP value before "Dual/Triple Front Camera"
        # Pattern: number + MP + (optional +) + Dual/Triple + Front Camera
        match = re.search(r'(\d+\.?\d*)\s*MP.*?(Dual|Triple)\s+Front\s*Camera',
                          spec, re.IGNORECASE)

        if match:
            mp_value = float(match.group(1))
            df.loc[idx, 'front_camera_mp'] = mp_value
            print(
                f"  Index {idx}: Extracted {mp_value} MP from {match.group(2)} Front Camera")

print(
    f"\n✓ Extracted {needs_dual_extraction.sum()} Dual/Triple front camera values")

Extracting Dual/Triple Front Camera values...
Phones with Dual/Triple Front Camera to extract: 22
  Index 56: Extracted 50.0 MP from Dual Front Camera
  Index 105: Extracted 50.0 MP from Dual Front Camera
  Index 236: Extracted 64.0 MP from Dual Front Camera
  Index 255: Extracted 50.0 MP from Dual Front Camera
  Index 268: Extracted 200.0 MP from Dual Front Camera
  Index 364: Extracted 50.0 MP from Dual Front Camera
  Index 439: Extracted 200.0 MP from Dual Front Camera
  Index 441: Extracted 50.0 MP from Dual Front Camera
  Index 541: Extracted 48.0 MP from Dual Front Camera
  Index 641: Extracted 64.0 MP from Dual Front Camera
  Index 649: Extracted 50.0 MP from Dual Front Camera
  Index 672: Extracted 200.0 MP from Dual Front Camera
  Index 687: Extracted 50.0 MP from Dual Front Camera
  Index 694: Extracted 64.0 MP from Dual Front Camera
  Index 729: Extracted 50.0 MP from Dual Front Camera
  Index 769: Extracted 48.0 MP from Dual Front Camera
  Index 852: Extracted 50.0 MP from 

C:\Users\Lappy\AppData\Local\Temp\ipykernel_768\3027906888.py:6: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  dual_front = df['Specifications'].str.contains(r'(Dual|Triple)\s+Front\s*Camera',


In [242]:
# Problem 27: Fill 0 for phones with "No Rear Camera"

print("Filling 0 for 'No Rear Camera' phones...")

# Find phones with "No Rear Camera" text
no_rear_camera = df['Specifications'].str.contains(
    'No Rear Camera', case=False, na=False)
missing_rear = df['rear_camera_mp'].isna()

needs_zero_fill = no_rear_camera & missing_rear

print(f"Phones with 'No Rear Camera': {needs_zero_fill.sum()}")

if needs_zero_fill.sum() > 0:
    print(f"Indices: {df[needs_zero_fill].index.tolist()}")

    # Fill with 0
    df.loc[needs_zero_fill, 'rear_camera_mp'] = 0.0

print(f"✓ Filled {needs_zero_fill.sum()} phones with 0 for rear_camera_mp")

Filling 0 for 'No Rear Camera' phones...
Phones with 'No Rear Camera': 20
Indices: [527, 562, 609, 680, 695, 711, 715, 718, 758, 823, 829, 835, 875, 876, 886, 945, 948, 959, 995, 1001]
✓ Filled 20 phones with 0 for rear_camera_mp


In [243]:
# Problem 28: Add column to indicate number of rear cameras

print("Adding column for rear camera count...")

# Create new column for rear camera count
df['rear_camera_count'] = 1  # Default single camera

# Extract camera count from specifications
camera_counts = {
    'Penta': 5,
    'Quad': 4,
    'Triple': 3,
    'Dual': 2
}

for camera_type, count in camera_counts.items():
    pattern = f'{camera_type}\\s+Rear'
    has_multi = df['Specifications'].str.contains(
        pattern, case=False, na=False, regex=True)
    df.loc[has_multi, 'rear_camera_count'] = count

# If rear_camera_mp is 0 or NaN, set count to 0
df.loc[df['rear_camera_mp'].isna() | (df['rear_camera_mp'] == 0),
       'rear_camera_count'] = 0

print("Rear camera count distribution:")
print(df['rear_camera_count'].value_counts().sort_index())

print("\n✓ Added rear_camera_count column")

Adding column for rear camera count...
Rear camera count distribution:
rear_camera_count
0     24
1    119
2    467
3    378
4     32
Name: count, dtype: int64

✓ Added rear_camera_count column


In [244]:
# Problem 29: Normalize OS names - remove decimal precision

print("Normalizing OS names (removing decimal precision)...")

# Count OS with decimal precision
os_with_decimal = df['operating_system'].str.contains(r'v\d+\.\d+',
                                                      case=False, na=False, regex=True)
print(f"OS values with decimal precision: {os_with_decimal.sum()}")

if os_with_decimal.sum() > 0:
    print("\nBefore normalization (sample):")
    print(df[os_with_decimal]['operating_system'].unique()[:10])

    # Remove decimal precision - keep only major version
    # Pattern: "Android v14.0" -> "Android v14"
    df['operating_system'] = df['operating_system'].str.replace(
        r'(v)(\d+)\.\d+', r'\g<1>\g<2>', regex=True
    )

    print("\nAfter normalization (sample):")
    print(df[df['operating_system'].notna()]['operating_system'].unique()[:10])

print("\n✓ Normalized OS names to integer versions only")

Normalizing OS names (removing decimal precision)...
OS values with decimal precision: 18

Before normalization (sample):
['Android v9.0' 'iOS v2.5.3' 'Android v8.1' 'Android v10.0' 'Android v6.0'
 'Android v13.0' 'Android v14.0' 'Android v7.1.2' 'Android v6.0.1'
 'Android v10.1']

After normalization (sample):
['Android v15' 'Android v16' 'Android v14' 'iOS v26' 'iOS v18' 'iOS v17'
 'Android v13' 'iOS v15' 'Android v10' 'Android v9']

✓ Normalized OS names to integer versions only


In [245]:
# Problem 30: Extract Symbian OS from specifications

print("Extracting Symbian OS...")

# Find phones with Symbian in specs
symbian_specs = df['Specifications'].str.contains(
    'Symbian', case=False, na=False)
missing_os = df['operating_system'].isna()

needs_symbian = symbian_specs & missing_os

print(f"Phones with Symbian OS to extract: {needs_symbian.sum()}")

if needs_symbian.sum() > 0:
    print(f"Indices: {df[needs_symbian].index.tolist()}")

    for idx in df[needs_symbian].index:
        spec = df.loc[idx, 'Specifications']

        # Extract Symbian version if available
        symbian_match = re.search(
            r'Symbian(?:\s+v?(\d+))?', spec, re.IGNORECASE)

        if symbian_match:
            if symbian_match.group(1):
                os_value = f"Symbian v{symbian_match.group(1)}"
            else:
                os_value = "Symbian"

            df.loc[idx, 'operating_system'] = os_value
            print(f"  Index {idx}: Extracted {os_value}")

print(f"\n✓ Extracted {needs_symbian.sum()} Symbian OS values")

Extracting Symbian OS...
Phones with Symbian OS to extract: 5
Indices: [941, 944, 948, 949, 950]
  Index 941: Extracted Symbian
  Index 944: Extracted Symbian v9
  Index 948: Extracted Symbian v30
  Index 949: Extracted Symbian
  Index 950: Extracted Symbian v30

✓ Extracted 5 Symbian OS values


In [255]:
# Problem 33: Add column for secondary front camera (Dual front camera)

print("Adding front_camera_secondary_mp column...")

# Create new column
df['front_camera_secondary_mp'] = 0.0  # Default: no secondary camera

# Find phones with dual/triple front cameras
dual_triple_front = df['Specifications'].str.contains(r'(Dual|Triple)\s+Front\s*Camera',
                                                      case=False, na=False, regex=True)

print(f"Phones with Dual/Triple Front Camera: {dual_triple_front.sum()}")

if dual_triple_front.sum() > 0:
    for idx in df[dual_triple_front].index:
        spec = df.loc[idx, 'Specifications']

        # Try to extract secondary camera value
        # Pattern: XX MP + YY MP ... Front Camera
        # Look for two MP values before "Front Camera"
        matches = re.findall(r'(\d+\.?\d*)\s*MP', spec)

        # Find the part with Front Camera
        if 'Front Camera' in spec:
            front_part = spec[spec.find('&'):] if '&' in spec else spec
            front_matches = re.findall(r'(\d+\.?\d*)\s*MP', front_part)

            # If we found multiple MP values before Front Camera
            if len(front_matches) >= 2:
                # First is primary (already in front_camera_mp)
                # Second is secondary
                secondary_mp = float(front_matches[1])
                df.loc[idx, 'front_camera_secondary_mp'] = secondary_mp

                if idx % 20 == 0:  # Show sample
                    print(
                        f"  Index {idx}: Primary={front_matches[0]} MP, Secondary={secondary_mp} MP")

print(f"\n✓ Added front_camera_secondary_mp column")
print(
    f"Phones with secondary front camera: {(df['front_camera_secondary_mp'] > 0).sum()}")

Adding front_camera_secondary_mp column...
Phones with Dual/Triple Front Camera: 22

✓ Added front_camera_secondary_mp column
Phones with secondary front camera: 22


C:\Users\Lappy\AppData\Local\Temp\ipykernel_768\3224585919.py:9: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  dual_triple_front = df['Specifications'].str.contains(r'(Dual|Triple)\s+Front\s*Camera',


In [256]:
# Problem 34: Convert resolution columns to Int64 (nullable integer)

print("Converting resolution columns to Int64...")

print(f"Before: resolution_width dtype = {df['resolution_width'].dtype}")
print(f"Before: resolution_height dtype = {df['resolution_height'].dtype}")

# Convert to Int64 (pandas nullable integer type)
df['resolution_width'] = df['resolution_width'].astype('Int64')
df['resolution_height'] = df['resolution_height'].astype('Int64')

print(f"\nAfter: resolution_width dtype = {df['resolution_width'].dtype}")
print(f"After: resolution_height dtype = {df['resolution_height'].dtype}")

print("\n✓ Converted resolution columns to Int64")

Converting resolution columns to Int64...
Before: resolution_width dtype = Int64
Before: resolution_height dtype = Int64

After: resolution_width dtype = Int64
After: resolution_height dtype = Int64

✓ Converted resolution columns to Int64


In [257]:
# Problem 35: Convert card_supported to Int64

print("Converting card_supported to Int64...")

print(f"Before: card_supported dtype = {df['card_supported'].dtype}")

# Convert to Int64 (pandas nullable integer type)
df['card_supported'] = df['card_supported'].astype('Int64')

print(f"After: card_supported dtype = {df['card_supported'].dtype}")

print("\n✓ Converted card_supported to Int64")

Converting card_supported to Int64...
Before: card_supported dtype = Int64
After: card_supported dtype = Int64

✓ Converted card_supported to Int64


In [258]:
# Problem 37: Add columns for secondary and tertiary rear cameras

print("Adding rear_camera_secondary_mp and rear_camera_tertiary_mp columns...")

# Initialize columns
df['rear_camera_secondary_mp'] = 0.0
df['rear_camera_tertiary_mp'] = 0.0

# Find phones with multiple rear cameras
multi_rear = df['rear_camera_count'] >= 2

print(f"Phones with 2+ rear cameras: {multi_rear.sum()}")

if multi_rear.sum() > 0:
    for idx in df[multi_rear].index:
        spec = df.loc[idx, 'Specifications']

        # Find the rear camera part (before "&" or "Rear")
        if 'Rear' in spec:
            # Extract all MP values before "Rear"
            rear_part = spec.split('&')[0] if '&' in spec else spec

            # Find all MP values in rear camera part
            mp_values = re.findall(r'(\d+\.?\d*)\s*MP', rear_part)

            # Only keep values that appear before "Front"
            if 'Front' in spec:
                front_pos = spec.find('Front')
                rear_part = spec[:front_pos]
                mp_values = re.findall(r'(\d+\.?\d*)\s*MP', rear_part)

            if len(mp_values) >= 2:
                # First is primary (already in rear_camera_mp)
                # Second is secondary
                df.loc[idx, 'rear_camera_secondary_mp'] = float(mp_values[1])

                if len(mp_values) >= 3:
                    # Third is tertiary
                    df.loc[idx, 'rear_camera_tertiary_mp'] = float(
                        mp_values[2])

                if idx % 100 == 0:  # Show sample
                    print(
                        f"  Index {idx}: {mp_values[0]}/{mp_values[1] if len(mp_values) > 1 else 0}/{mp_values[2] if len(mp_values) > 2 else 0} MP")

print(f"\n✓ Added rear camera secondary/tertiary columns")
print(
    f"Phones with secondary rear camera: {(df['rear_camera_secondary_mp'] > 0).sum()}")
print(
    f"Phones with tertiary rear camera: {(df['rear_camera_tertiary_mp'] > 0).sum()}")

Adding rear_camera_secondary_mp and rear_camera_tertiary_mp columns...
Phones with 2+ rear cameras: 877
  Index 0: 200/12/0 MP
  Index 100: 50/2/8 MP
  Index 200: 50/2/16 MP
  Index 300: 200/12/0 MP


  Index 400: 50/2/8 MP
  Index 500: 12/5/20 MP
  Index 600: 108/8/2 MP
  Index 700: 50/2/8 MP
  Index 800: 50/2/16 MP
  Index 1000: 50/2/8 MP

✓ Added rear camera secondary/tertiary columns
Phones with secondary rear camera: 877
Phones with tertiary rear camera: 773


In [275]:
# Create device_type (VERY IMPORTANT)

# keypad phones usually have very small display & no OS
df['device_type'] = 'smartphone'

df.loc[
    (df['display_size_inches'] <= 3) | 
    (df['operating_system'].isna()),
    'device_type'
] = 'feature_phone'

df['device_type'].value_counts()


device_type
smartphone       932
feature_phone     88
Name: count, dtype: int64

In [276]:
df

Product_Name   Price  Rating  Spec_Score  has_3g  has_4g  \
0     Samsung Galaxy S25 Ultra  108460    4.15          93       1       1   
1        Samsung Galaxy S25 FE   59999    4.70          86       1       1   
2         OnePlus Nord CE 5 5G   24998    4.10          83       1       1   
3              Realme Narzo 90   16999    4.40          72       1       1   
4                Vivo T3 Ultra   22799    4.10          82       1       1   
...                        ...     ...     ...         ...     ...     ...   
1015               Vivo Y28 5G   14499    4.05          75       1       1   
1016               itel A70 4G    8989    4.60          60       1       1   
1017         Motorola Moto G04    7999    4.35          64       1       1   
1018                  Poco C65    9850    4.20          74       1       1   
1019               itel it5330    1663    4.45          14       0       0   

      has_5g  has_nfc  has_ir_blaster       processor_name  ...  \
0          1        1               0   Snapdragon 8 Elite  ...   
1          1        1               0          Exynos 2400  ...   
2          1        0               1  Dimensity 8350 Apex  ...   
3          1        0               0   Dimensity 6400 Max  ...   
4          1        0               0  Dimensity 9200 Plus  ...   
...      ...      ...             ...                  ...  ...   
1015       1        0               0       Dimensity 6020  ...   
1016       0        0               0          Unisoc T603  ...   
1017       0        0               0          Unisoc T606  ...   
1018       0        0               0            Helio G85  ...   
1019       0        0               0                  NaN  ...   

     rear_camera_mp  rear_camera_secondary_mp  rear_camera_tertiary_mp  \
0             200.0                      12.0                      0.0   
1              50.0                      12.0                      8.0   
2              50.0                       8.0                     16.0   
3              50.0                       2.0                     50.0   
4              50.0                       8.0                     50.0   
...             ...                       ...                      ...   
1015           50.0                       2.0                      8.0   
1016           13.0                       8.0                      0.0   
1017           16.0                       0.0                      0.0   
1018           50.0                       2.0                      8.0   
1019            3.0                       0.0                      0.0   

      rear_camera_count  card_supported  operating_system  \
0                     4               0       Android v15   
1                     3               0       Android v16   
2                     2               1       Android v15   
3                     2               1       Android v15   
4                     2               1       Android v14   
...                 ...             ...               ...   
1015                  2               1       Android v13   
1016                  2               1       Android v13   
1017                  1               1       Android v14   
1018                  3               1       Android v13   
1019                  1               1               NaN   

                                           Product_Link  \
0     https://www.smartprix.com/mobiles/samsung-gala...   
1     https://www.smartprix.com/mobiles/samsung-gala...   
2     https://www.smartprix.com/mobiles/oneplus-nord...   
3     https://www.smartprix.com/mobiles/realme-narzo...   
4     https://www.smartprix.com/mobiles/vivo-t3-ultr...   
...                                                 ...   
1015  https://www.smartprix.com/mobiles/vivo-y28-5g-...   
1016  https://www.smartprix.com/mobiles/itel-a70-4g-...   
1017  https://www.smartprix.com/mobiles/motorola-mot...   
1018  https://www.smartprix.com/mobiles/poco-c65-6gb...   
1019 

In [267]:
# Problems 38-40: Final data quality verification

print("=== FINAL DATA QUALITY CHECKS ===\n")

print("1. Missing values summary:")
missing = df.isnull().sum()
missing = missing[missing > 0].sort_values(ascending=False)
print(missing)

print("\n2. Data types:")
print(df.dtypes)

print("\n3. New columns added:")
new_cols = ['rear_camera_count', 'front_camera_secondary_mp',
            'rear_camera_secondary_mp', 'rear_camera_tertiary_mp',
            'card_extended_upto_gb']
for col in new_cols:
    if col in df.columns:
        print(f"  ✓ {col}")

print("\n4. Dataset shape:")
print(f"  Rows: {df.shape[0]}")
print(f"  Columns: {df.shape[1]}")

print("\n✓ All quality checks passed")

=== FINAL DATA QUALITY CHECKS ===

1. Missing values summary:
display_frequency_hz     151
cpu_speed_ghz             77
operating_system          77
front_camera_mp           62
cores                     56
fast_charging_speed_w     53
processor_name            52
resolution_width           9
resolution_height          9
ram_gb                     7
rom_gb                     6
rear_camera_mp             4
dtype: int64

2. Data types:
Product_Name                  object
Price                          int64
Rating                       float64
Spec_Score                     int64
has_3g                         int64
has_4g                         int64
has_5g                         int64
has_nfc                        int64
has_ir_blaster                 int64
processor_name                object
cores                         object
cpu_speed_ghz                float64
ram_gb                       float64
rom_gb                       float64
battery_capacity_mah           int64
fast_c

In [277]:
# Optional: Reorder columns for better readability

print("Reordering columns for better organization...")

column_order = [
    # Basic Info
    'Product_Name', 'Price', 'Rating', 'Spec_Score', 

    # Connectivity
    'has_dual_sim', 'has_3g', 'has_4g', 'has_5g', 'has_nfc', 'has_ir_blaster',

    # Processor
    'processor_name', 'cores', 'cpu_speed_ghz',

    # Memory
    'ram_gb', 'rom_gb',

    # Battery
    'battery_capacity_mah', 'fast_charging_available', 'fast_charging_speed_w',

    # Display
    'display_size_inches', 'resolution_width', 'resolution_height', 'display_frequency_hz',

    # Cameras
    'front_camera_mp', 'front_camera_secondary_mp',
    'rear_camera_mp', 'rear_camera_secondary_mp', 'rear_camera_tertiary_mp', 'rear_camera_count',

    # Memory Card
    'card_supported', 'card_extended_upto_gb',

    # OS
    'operating_system',

    # Reference
    'Product_Link', 'Image_URL', 'Specifications', 'device_type'
]

# Reorder (only include columns that exist)
existing_cols = [col for col in column_order if col in df.columns]
df = df[existing_cols]

print(f"✓ Columns reordered")
print(f"\nColumn order:")
for i, col in enumerate(df.columns, 1):
    print(f"  {i:2d}. {col}")

# Save with reordered columns
df.to_csv('smartprix_mobiles_cleaned_final.csv', index=False)
print(f"\n✓ Saved with reordered columns")

Reordering columns for better organization...
✓ Columns reordered

Column order:
   1. Product_Name
   2. Price
   3. Rating
   4. Spec_Score
   5. has_3g
   6. has_4g
   7. has_5g
   8. has_nfc
   9. has_ir_blaster
  10. processor_name
  11. cores
  12. cpu_speed_ghz
  13. ram_gb
  14. rom_gb
  15. battery_capacity_mah
  16. fast_charging_available
  17. fast_charging_speed_w
  18. display_size_inches
  19. resolution_width
  20. resolution_height
  21. display_frequency_hz
  22. front_camera_mp
  23. front_camera_secondary_mp
  24. rear_camera_mp
  25. rear_camera_secondary_mp
  26. rear_camera_tertiary_mp
  27. rear_camera_count
  28. card_supported
  29. operating_system
  30. Product_Link
  31. Image_URL
  32. Specifications
  33. device_type

✓ Saved with reordered columns


---
---
---


<center> <span style="font-size: 36px;"> <b>After all the cleaning

In [278]:
cleaned_smartphone = pd.read_csv('smartprix_mobiles_cleaned_final.csv')

In [279]:
cleaned_smartphone.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 33 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Product_Name               1020 non-null   object 
 1   Price                      1020 non-null   int64  
 2   Rating                     1020 non-null   float64
 3   Spec_Score                 1020 non-null   int64  
 4   has_3g                     1020 non-null   int64  
 5   has_4g                     1020 non-null   int64  
 6   has_5g                     1020 non-null   int64  
 7   has_nfc                    1020 non-null   int64  
 8   has_ir_blaster             1020 non-null   int64  
 9   processor_name             968 non-null    object 
 10  cores                      964 non-null    object 
 11  cpu_speed_ghz              943 non-null    float64
 12  ram_gb                     1013 non-null   float64
 13  rom_gb                     1014 non-null   float